### ISSUE TITLE
Some st issues

### ISSUE THREAD

**Issue by dankehidayat** [LukeSmithxyz/st#10]
st somehow can't use del keys and it have some pasting issues. When pasting, the text somehow got cutted half of the word. Is this a common issues on st ?

**Comment by dankehidayat** [comment]
Also the block move slower compared when i use the LARBS.

**Comment by LukeSmithxyz** [comment]
The delete key is not mapped. I can't understand anything else you're trying to say.

**Comment by dankehidayat** [comment]
So what i'd just need is to map the delete keys. Sorry if i confuse you
