### ISSUE TITLE
Copy from ST, paste to Chromium or Brave extremely slow

### ISSUE THREAD

**Issue by ryanerwin** [LukeSmithxyz/st#103]
This is a really odd issue... When pasting text from ST to Chromium or Brave, it hangs usually for several seconds... When pasting into more complex forms say with a built in text editor, it often hangs completely. Often the paste even fails.

The thing is, when I check what's in the clipboard from either ST or Konsole, I'm getting the EXACT same value.

```
 ❯ xclip -out -selection clipboard | xxd
```

<details>
  <summary>`xclip -out -selection clipboard | xxd`</summary>

```
00000000: 20e2 9daf 2078 636c 6970 202d 6f75 7420   ... xclip -out
00000010: 2d73 656c 6563 7469 6f6e 2063 6c69 7062  -selection clipb
00000020: 6f61 7264 207c 2078 7864 2020 2020 2020  oard | xxd
00000030: 2020 2020 2020 2020 2020 2020 2020 2020
00000040: 2020 2020 2020 2020 2020 2020 2020 2020
00000050: 2020 2020 2020 2020 2020 2020 2020 2020
00000060: 2020 2020 2020 2020 2020 2020 2020 2020
00000070: 2020 2020 2020 2020 2020 2020 2020 2020
00000080: 2020 2020 2020 2020 2020 2020 2020 20ee                 .
00000090: 82b2 2049 4e53 4552 5420 200a            .. INSERT  .
```

</details>

<details>
  <summary>Comparing the clipboard contents</summary>

```
 ❯ md5sum clipboard-from-*
c2ac087caedc2e05eb5470655e6995af  clipboard-from-konsole
c2ac087caedc2e05eb5470655e6995af  clipboard-from-st
```

</details>

Ironically, if I copy the exact same text from ST, paste in Konsole, then copy from Konsole and paste into my browser, it's again instant. It's slow to paste into Firefox, but much slower to paste into Chromium (and Brave).

Note, in this screencast Chromium hangs for about 30 seconds each time I paste... Hang in there and you'll see ;-)
![Konsole_vs_ST](https://user-images.githubusercontent.com/2156415/59973529-4af54b00-95cb-11e9-8c0c-37db2af51b2e.gif)

I tried the [Clipboard Patch](https://st.suckless.org/patches/clipboard/), but it's not related... Still get the same behavior.

For now, I've found the lag pasting into Firefox isn't quite as bad.
Also, pasting via `xclip -selection clipboard` works normally (no lag).

Any ideas?

**Comment by Mati20187** [comment]
Try ALT+C CTRL+V

**Comment by ryanerwin** [comment]
For me, <kbd>alt</kbd>+<kbd>c</kbd> doesn't copy the current selection inside the ST window to the clipboard. My Desktop Environment is KDE rather than i3.

Note that if I use `xclip` from inside ST to copy command output directly to the clipboard, it works fine.

Maybe I can tweak `x.c`'s `void clipcopy`...

**Comment by codeitlikemiley** [comment]
i have weird issue also only happens in ST not in gnome-terminal
when i use rofi, and it types automatically for you the characters will freeze at some point
you need to press other key so that the characters that have been type will be showed

**Comment by DrWursterich** [comment]
I have the same problem on one of my machines. I have observed, that pressing another button while focusing the terminal where I copied from after pasting immediately ends this "freeze" and pasts the contents.
What I think might also be connected to this issue, is, that after holding a key or key-combination for some time and releasing it, the same key gets pressed whenever I press any (other) key. This effect lasts for a certain amount of keystrokes, but the longer the initial key(-combination) was pressed, the more keystrokes are needed, to get rid of it.
On other machines I fail to reproduce these issues.

**Comment by FilipLitwora** [comment]
I have a pretty similar problem, but when i paste something longer (30 chars) to st

**Comment by codeitlikemiley** [comment]
try my fixed to it ...  see if this works issue with gnome apps
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS
DISPLAY XAUTHORITY

**Comment by hallzy** [comment]
I too am having this problem. Just to be clear, I am not using Luke's build but this issue seems to actually be with st.

The last commit version I found that works is 75f92eb3489275bfcad901e5ca424134eda6e2f4

The commit that seems to have caused this issue has the commit message 'better input method editor (IME) support'

I intend to look more into the changeset later

**Comment by LukeSmithxyz** [comment]
Now I've never been able to replicate this problem on Brave/st on my machines.

Can anyone say if this patch https://github.com/LukeSmithxyz/st/pull/85 fixes it for you?

**Comment by DrWursterich** [comment]
Yes, it does!

**Comment by LukeSmithxyz** [comment]
Okay. I'll merge it.
