### ISSUE TITLE
Copying with Alt+O doesn't work on my computer :-(

### ISSUE THREAD

**Issue by pwittchen** [LukeSmithxyz/st#104]
Hi,

First of all, very cool terminal emulator! I watched this video: https://www.youtube.com/watch?v=5E9bO5ZURcs (along with other videos :-D). It works fine. <kbd>Alt+L</kbd> shortcut for links also works fine, but <kbd>Alt+O</kbd> doesn't work.

Steps to reproduce the issue:
1. start `st`
2. type `ls -a`
3. see list of the files in current dir
4. hit <kbd>Alt+O</kbd>
5. `dmenu` opens
6. see message `Copy which command's output?`
7. I see **no commands to choose from**

Expected result:
- I'd like to see any command to choose

Currently I'm (still) using Ubuntu 18.04.2 LTS.

**Comment by Mati20187** [comment]
I can't reproduce this issue on my system. 
Make sure you have _xclip_ installed. If it still doesn't work, try my fork: https://gitlab.com/Matii/st

**Comment by pwittchen** [comment]
I installed Arch and I still see the same issue. :-)

**Comment by Mati20187** [comment]
Have you tried what I told you?

**Comment by pwittchen** [comment]
I have `xclip` installed, but I haven't tried your fork.

**Comment by pwittchen** [comment]
Probably I'll give up using this terminal emulator and I'll write such functionality for myself as a separate script, so I can use it in any terminal emulator - not only this one, because general idea is quite interesting and seems to be useful :-).

**Comment by LukeSmithxyz** [comment]
What does your commend prompt look like?

**Comment by pwittchen** [comment]
It looks like that:

![pic1](https://user-images.githubusercontent.com/695319/60772462-1d45f100-a0f7-11e9-9ba5-94c40e07d1f7.png)

I don't know how to take a screenshot while dmenu is open, so I took a picture of it with my phone :D

![pic2](https://user-images.githubusercontent.com/695319/60772473-42d2fa80-a0f7-11e9-9e06-2b101c7298a2.jpg)

**Comment by LukeSmithxyz** [comment]
External pipe functions won't work properly with tmux.

**Comment by pwittchen** [comment]
Ok. Thanks for the reply, so now I know what was wrong.
