### ISSUE TITLE
Default foreground, background, cursor, reverse cursor color dynamic support?

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/st#108]
I was updating my `st` build today from upstream (`github.com/LukeSmithxyz/st`) and I noticed this change

```diff
@@ -113,9 +118,9 @@ static const char *colorname[] = {
  * Default colors (colorname index)
  * foreground, background, cursor, reverse cursor
  */
-unsigned int defaultfg = 15;
-unsigned int defaultbg = 0;
-static unsigned int defaultcs = 15;
+unsigned int defaultfg = 257;
+unsigned int defaultbg = 256;
+static unsigned int defaultcs = 258;
 static unsigned int defaultrcs = 0;
 
 /*
```

it probably was introduced earlier than st's 0.8.2 version, since I last updated 9 weeks ago.

What this means is that you can't set the default `foreground`, `background`, `cursor` and `reverse cursor` colors through `~/.Xdefaults` or `~/.Xresources` anymore.
(Before they were set by `*.color15` and `*.color0`)

---

I tried adding this to my `~/.Xdefaults`:

```console
!! background
*.color257: black
*.color17: black
*.defaultbg: black

!! foreground
*.color256: white
*.color16: white
*.defaultfg: white

!! cursor
*.color258: white
*.color18: white
*.defaultcs: white
```

but it does NOT work.

The only way you can change the defaults now is manually editing the `config.h` inside `st`, which is fine, but not really portable (AUR etc.), and now this build is no longer fully compatible with dynamic color support.

Could we make a work-around to be able to set the defaults through Xdefaults or Xresources?

I maybe could make a PR, but I don't know how the dynamic color[0-15] handling is working / where it is.

Related: #97

**Comment by sarpik** [comment]
Nevermind, I found the fix!

```console
!! background
*.background: #282828

!! foreground
*.foreground: white

!! cursor
*.cursorColor: white
```

For anyone curious why this happened, take a look at this bad boy:

```c
/*
 * Xresources preferences to load at startup
 */
ResourcePref resources[] = {
		{ "font",         STRING,  &font },
		{ "fontalt0",     STRING,  &font2[0] },
		{ "color0",       STRING,  &colorname[0] },
		{ "color1",       STRING,  &colorname[1] },
		{ "color2",       STRING,  &colorname[2] },
		{ "color3",       STRING,  &colorname[3] },
		{ "color4",       STRING,  &colorname[4] },
		{ "color5",       STRING,  &colorname[5] },
		{ "color6",       STRING,  &colorname[6] },
		{ "color7",       STRING,  &colorname[7] },
		{ "color8",       STRING,  &colorname[8] },
		{ "color9",       STRING,  &colorname[9] },
		{ "color10",      STRING,  &colorname[10] },
		{ "color11",      STRING,  &colorname[11] },
		{ "color12",      STRING,  &colorname[12] },
		{ "color13",      STRING,  &colorname[13] },
		{ "color14",      STRING,  &colorname[14] },
		{ "color15",      STRING,  &colorname[15] },
		{ "background",   STRING,  &colorname[256] },
		{ "foreground",   STRING,  &colorname[257] },
		{ "cursorColor",  STRING,  &colorname[258] },
		{ "termname",     STRING,  &termname },
		{ "shell",        STRING,  &shell },
		{ "xfps",         INTEGER, &xfps },
		{ "actionfps",    INTEGER, &actionfps },
		{ "blinktimeout", INTEGER, &blinktimeout },
		{ "bellvolume",   INTEGER, &bellvolume },
		{ "tabspaces",    INTEGER, &tabspaces },
		{ "borderpx",     INTEGER, &borderpx },
		{ "cwscale",      FLOAT,   &cwscale },
		{ "chscale",      FLOAT,   &chscale },
		{ "alpha",        FLOAT,   &alpha },
};
```

I'll make a PR to include an example for setting the bg, fg, cursor & reverse cursor soon:)

**Comment by aleksfadini** [comment]
How is that solved? st now doesnt work with pywal anymore.

**Comment by sarpik** [comment]
@aleksfadini umm I don't know, I haven't used `pywal`.
What's the color scheme that you're using with `wal`?

**Comment by aleksfadini** [comment]
I'm using 
```
bw="wal -c && wal -i ~/.config/wall.png
```
So the colors depend on the image that is in my config. That's how Luke set it up in Larbs a few months ago before he moved on :)
I really like that everything is themed after switching the wall.png image (from a script).
Unfortunately lately I have to close all my instances of st and reopen them, because they change their background from a dark transparent color to a different new color that is often impossible to read.
All other terminals behaved perfectly (termite, urxvt...) except st in this regard. It used to work. Any ideas?

**Comment by sarpik** [comment]
Yeah, I haven't merged larbs' updates into my fork yet and so haven't had a chance to use `[py]wal`..
Also, I don't really have as much experience w/ `st`, so I'm afraid I cannot help:S
