### ISSUE TITLE
Strange .Xdefaults colors

### ISSUE THREAD

**Issue by Taborater** [LukeSmithxyz/st#110]
After `sudo make install` I get this colors 
![sc](https://user-images.githubusercontent.com/17968282/60621573-afdc4c80-9de6-11e9-81b6-13a3323946b3.png)

I tried to change values in `.Xdefaults` and everything works nice, except colors.
I used pywal before, but I removed it from `.xinitrc` and `.bashrc`

**Comment by Mati20187** [comment]
First, copy the .Xdefaults contents into .Xresources. Then, remove .Xdefaults and create a symlink: 
ln -s .Xresources .Xdefaults
Also, post the file on pastebin or something like that and send me a link

**Comment by Taborater** [comment]
`.Xresources`: https://pastebin.com/xPvTtfnt

**Comment by Mati20187** [comment]
Everything is fine. Your colorscheme is gruvbox. If you want to change it, comment out the lines with gruvbox colors and uncomment the ones you want

**Comment by Taborater** [comment]
And how can I colorized my prompt?

**Comment by Taborater** [comment]
Thanks! And how can I colorize my prompt?

**Comment by Mati20187** [comment]
https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/

**Comment by Mati20187** [comment]
https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/

**Comment by Taborater** [comment]
Thanks
