### ISSUE TITLE
dot lines instead of straight line

### ISSUE THREAD

**Issue by dagnachewa** [LukeSmithxyz/st#111]
Hello
In weechat I have a dot line instead of a straight line, and I tried to add this patch https://st.suckless.org/patches/boxdraw/, it did not work.
Can you try to add this patch to your well maintained fork ?
Thank you

**Comment by Mati20187** [comment]
Try my fork: https://gitlab.com/Matii/st
It's basically Luke's one with a few modifications (mainly, the boxdraw patch)

**Comment by dagnachewa** [comment]
thanks Mati20187 it worked weechat now has a full line not doted thanks a lot

**Comment by dagnachewa** [comment]
does yout fork support true color ?
when I try to change terminal color with pywal the current color has a
white background
when am in weechat, for exemple, I dont want to close and restart weechat
to enjoy the new colors

with others forks or other terminal pywal changes the right colour without
having a white background on the current shell

can you try if you have the same issue ?

**Comment by Mati20187** [comment]
> does yout fork support true color ? when I try to change terminal color with pywal the current color has a white background when am in weechat, for exemple, I dont want to close and restart weechat to enjoy the new colors with others forks or other terminal pywal changes the right colour without having a white background on the current shell can you try if you have the same issue ?

It's not the fork's issue. Getting st and pywal to work well together is a hassle. I used to use pywal, but when I switched to st, I decided to pick a few good themes and I switch between them in .Xresources. 
If you really want to use pywal, though, you can try [this](https://github.com/dylanaraps/pywal/wiki/Customization#st). Sometimes you can get it to work, but it often is a pain. I hope it'll work for you :)

**Comment by dagnachewa** [comment]
thank a lot

**Comment by dagnachewa** [comment]
how do you manage clicking of url links ?
