### ISSUE TITLE
Ranger image previews do not work with this fork

### ISSUE THREAD

**Issue by tonijarjour** [LukeSmithxyz/st#115]
They do work with unmodified st. But not with this. Don't really know what other information to give.

**Comment by geolimber** [comment]
Same issue. In ranger and images in w3m browser. Suppose this might be caused by transparency patch.
I am using i3wm, which does not support transparency like i3-gapps.

**Comment by mssx86** [comment]
>I am using i3wm, which does not support transparency like i3-gapps. 
eh? that's bound to the compositor, not to the wm.

**Comment by tonijarjour** [comment]
When I tested this, I was using bspwm.

**Comment by Mati20187** [comment]
Try ueberzug instead of w3m

**Comment by antenore** [comment]
It works for me

**Comment by antenore** [comment]
Have a look at my files, hope it helps https://github.com/antenore/dotfiles

**Comment by kevteg** [comment]
Not working for me either with bspwm

**Comment by castrated** [comment]
works on my machine
