### ISSUE TITLE
x.c error resources

### ISSUE THREAD

**Issue by 9hozt** [LukeSmithxyz/st#12]
➜  st git:(master) ✗ make
st build options:
CFLAGS  = -I/usr/X11R6/include  -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/uuid   -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -DVERSION="0.8.1" -D_XOPEN_SOURCE=600 -O
LDFLAGS = -L/usr/X11R6/lib -lm -lrt -lX11 -lutil -lXft -lXrender  -lfontconfig -lfreetype   -lfreetype
CC      = c99
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.1\" -D_XOPEN_SOURCE=600 -O -c x.c
x.c: Dans la fonction « config_init »:
x.c:1999:11: error: « resources » non déclaré (première utilisation dans cette fonction); vouliez-vous utiliser « resource_load » ?
  for (p = resources; p < resources + LEN(resources); p++)
           ^~~~~~~~~
           resource_load
x.c:1999:11: note: chaque identificateur non déclaré est rapporté une seule fois pour chaque fonction dans laquelle il apparaît
make: *** [Makefile:22: x.o] Error 1

From a fresh clone

**Comment by LukeSmithxyz** [comment]
What distro do you have? It looks like you don't have one of the build dependencies. Be sure you have the devel packages of those listed in the README, I think you need the fontconfig build packages too.
