### ISSUE TITLE
I-beam cursor

### ISSUE THREAD

**Issue by azzamsa** [LukeSmithxyz/st#121]
Can we have I beam cursor ?

I know we have `*.cursorColor: white`, is there something like `*.cursorType: i-beam`

Thanks in advance

**Comment by decantr** [comment]
Change line [131](https://github.com/LukeSmithxyz/st/blob/master/config.h#L131) `cursorshape` in the config.h file to `6` and recompile.

**Comment by azzamsa** [comment]
Wow, work great.

Btw, do you know why we use "recompile" approach rather than reading config from dotfiles? is this approach taken to reduce the code base lines?

**Comment by decantr** [comment]
I think it's mainly that yeah, most of their programs are under 2k loc. Also config files are bloat.
