### ISSUE TITLE
 Xresources configs can't be loaded via #include

### ISSUE THREAD

**Issue by mi-lad** [LukeSmithxyz/st#123]
If I save my st related Xresources configs in a separate file and load them in my `.Xresources` via `#include ".Xresources.d/st" things break: The configurations are not loaded but even worse, the content of `.Xresources` is modified: all quotation marks in lines that contain `#include` are removed.

**Comment by decantr** [comment]
Just tested this and it works fine for me. 
At what point is the `.Xresources` file changed, when you open another instance of `st`?

**Comment by mi-lad** [comment]
You're right. This is actually [a bug in Manjaro i3](https://github.com/oberon-manjaro/i3-scripts/issues/2)

**Comment by mvanorder** [comment]
How is this closed pointing to an issue that's closed pointing to this issue?
