### ISSUE TITLE
Changing Default colors and font size

### ISSUE THREAD

**Issue by Jesse415** [LukeSmithxyz/st#124]
First, I really love your work. I use it as a base as to what I would like on my system and customize it accordingly to my needs. 

I've been stuggling to make the defaults to my settings. I can run xrdb .Xresources and the terminal will change colors but on reboot it will change back to default. Also, I have not been able to change the font size. I can seem to figure out why it resets. Thank you for the help in advance.

**Comment by Tulkdan** [comment]
You need to run `xrdb .Xresources` everytime you boot up you pc.
The location that you can change you font size and font is in the config.h file, if you read it the comments you can make some changes that you'd like.

**Comment by Jesse415** [comment]
Ah, I see. I got it from the AUR. I have to change it and build it myself. Got ya, Thank you.

**Comment by LukeSmithxyz** [comment]
My build does not require a recompile for color changes. Just have xrdb run in your login profile or xprofile, etc.
