### ISSUE TITLE
error when run cat ~/.config/emoji

### ISSUE THREAD

**Issue by smikeblog** [LukeSmithxyz/st#125]
Hi, Luke!
There is smth wrong in st
the error when I run st from default terminal - gnome-terminal on Manjaro
give 
~ ❯❯❯ st
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  4315
  Current serial number in output stream:  4467
                                      
The emoji is your emoji file
On tilix or gnome-terminal there is no error and terminal doesn'n crash.

**Comment by Tulkdan** [comment]
I was able to fix it downloading the font [Symbola](https://fontlibrary.org/en/font/symbola) that have a lot of representations for emojis

**Comment by smikeblog** [comment]
Thanks!
I installed symbola font but unfortunately that doesn't solve the problem. cat command crashed the terminal.

**Comment by mamg22** [comment]
This error seems to be from Xft (the font drawing library) and not from st, as noted in [st's FAQ](https://git.suckless.org/st/file/FAQ.html#l168), there it suggests to either not use color emoji fonts, disable its usage in the fontconfig configuration or use the ugly workaround (which I use and can say it works perfectly), by adding it in one of the font loading functions in x.c

**Comment by kevteg** [comment]
I haven't been able to solve this issue, nor with the ugly workaround and neither installing a new font :/

**Comment by LukeSmithxyz** [comment]
https://github.com/LukeSmithxyz/voidrice/issues/284

**Comment by madobet** [comment]
> This error seems to be from Xft (the font drawing library) and not from st, as noted in [st's FAQ](https://git.suckless.org/st/file/FAQ.html#l168), there it suggests to either not use color emoji fonts, disable its usage in the fontconfig configuration or use the ugly workaround (which I use and can say it works perfectly), by adding it in one of the font loading functions in `x.c`, but it makes emoji colorless or render as a square.
> 
> For those who want to use the ugly workaround, The code suggested in the FAQ requires that there is a FcPattern called fcpattern, and there's only one function that has that: `xmakeglyphfontspecs`, so I added it after `FcPatternAddBool(fcpattern, FC_SCALABLE, 1);` a little before line 1400, if someone thinks there's a better place to put it, tell me

There is a function call: `FcPatternAddBool(fcpattern, FC_SCALABLE, 1);` in `x.c`, so I changed it to `FcPatternAddBool(fcpattern, FC_SCALABLE, FcFalse);`. compiled st again, it works but emoji will disappear?
