### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/st#129]
I am using the following locale settings on my system

LANG=en_US.UTF-8
LC_TIME=sr_RS.UTF-8@latin

when I ls -la it displays y after the month. 
https://0x0.st/zvem.png while everywhere else in the terminal it displays the date and time properly ...

I wonder if the solution is plain simple like wit https://github.com/LukeSmithxyz/mutt-wizard/issues/296#issue-499158596 :D

**Comment by LukeSmithxyz** [comment]
I don't know what would cause this issue, but it is hard to imagine that it is related to your terminal emulator at all. This is something between `ls` and your locale.

**Comment by kronikpillow** [comment]
Ok ... thanks for the reply ^^
