### ISSUE TITLE
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)

### ISSUE THREAD

**Issue by kevinaltaf** [LukeSmithxyz/st#130]
I tried to open the st terminal and open the configuration polybar via vim and I searched for /poly and suddenly the terminal came out,
and there is a message , but in xfce4-terminal it's fine with vim

X Error of failed request: BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request: 139 (RENDER)
  Minor opcode of failed request: 20 (RenderAddGlyphs)
  Serial number of failed request: 1943
  Current serial number in output stream: 2071

os : Arch
wm : i3-gaps
![2019-09-29-103932_1366x768_scrot](https://user-images.githubusercontent.com/47493498/65825892-b6277b00-e2a6-11e9-8367-dd2c5a4916f2.png)

my st version :  st-0.8.2

**Comment by LukeSmithxyz** [comment]
https://github.com/LukeSmithxyz/voidrice/issues/284

**Comment by grahamgower** [comment]
It would be nice if the terminal didn't crash simply because of a missing font.

**Comment by anuraggupta816** [comment]
git init
	echo foo >foo
	git add foo
	git commit -m foo
	# The following assumes bash builtin echo
	echo -e '\u2754' >foo
	gitk
https://www.spinics.net/lists/git/msg379512.html

**Comment by flyingpeakock** [comment]
I fixed it by uninstalling noto-fonts-emoji

**Comment by MamunPW01** [comment]
`apt remove --purge fonts-noto-color-emoji` worked for me. :)

**Comment by qbitroot** [comment]
> `apt remove --purge fonts-noto-color-emoji` worked for me. :)

While this solution can work, it also removes colorful emojis for other applications, like web browsers and emojis become ugly. I font [another solution](https://teracontent.com/how-to-fix-badlength-poly-request-too-large-error/): `sudo pacman -S bdf-unifont`
It fixed for me.

**Comment by rangerzhou** [comment]
```
sudo apt install unifont
```

It worked for me...

**Comment by RichieOrito** [comment]
anyone having the problem `sudo apt install unifont` really works

**Comment by LetMeByte** [comment]
Coming here having the same problem, I see the solution has been found and can indeed confirm it's succesful application.

Can be closed.

**Comment by zaquestion** [comment]
using the [font2](https://st.suckless.org/patches/font2/) patch (and a fallback to noto) was the best move for me, for those coming here with similar issues but their on `config.h` stuff

**Comment by andorian8** [comment]
Same for me. I had a similar error with `gitk`after creating a new Laravel 9 project.
```sudo apt install unifont```
worked for me. That's interesting because I had no commits with emoji in messages. And `gitk` worked fine with other projects on the same computer.

**Comment by acm19** [comment]
This workaround: https://git.suckless.org/dwm/commit/970f37697358574e127019eb0ee2f5725ec05ce0.html#h0-1-3 or updating Xtf to 2.3.5 or superior should fix it as well: https://gitlab.freedesktop.org/xorg/lib/libxft/-/blob/libXft-2.3.5/NEWS.

**Comment by stephanmg** [comment]
Ubuntu 20 here:` sudo apt install unifont` works.
