### ISSUE TITLE
Cannot patch "st-delkey-0.8.2.diff"

### ISSUE THREAD

**Issue by ncavasin** [LukeSmithxyz/st#133]
As the title says, every time i press the Del key st inserts `[P` instead of deleting the current character.

Went to the suckless [site](https://st.suckless.org/patches/delkey/) and downloaded the corresponding [patch](https://st.suckless.org/patches/delkey/st-delkey-20160727-308bfbf.diff) . Run `make clean` and then  `patch -Np1 patch_filename.diff`. This is the output i got:
 

```
patching file config.def.h
Hunk #1 FAILED at 261.
Hunk #2 FAILED at 316.
2 out of 2 hunks FAILED -- saving rejects to file config.def.h.rej
patching file st.info
Hunk #1 FAILED at 53.
Hunk #2 FAILED at 73.
2 out of 2 hunks FAILED -- saving rejects to file st.info.rej
```

After that i run `diff -y config.def.h config.def.h.rej` and `diff -y st.info st.info.rej` and manually edited the lines of the corresponding files. Finally, run `sudo make install` and gave it a try. 

It still doesn't work and i don't know why. Any help will be appreciated.

Thanks in advance!

**Comment by M4444** [comment]
The `Delete` key isn't an **st** problem but most likely a **shell** problem.
The patch you applied changes the behavior to an ancient one that 99% of user wouldn't want today.

Just removing the patch and running:
```
tput smkx
```
should fix the problem if you are running **bash**.

For more information and a fix for **zsh** see the [FAQ](https://git.suckless.org/st/file/FAQ.html#l25) file from the original source repo.
