### ISSUE TITLE
dmenu -w "$WINDOWID" doesn't work on this fork, breaking unicode codepoint input

### ISSUE THREAD

**Issue by brckts** [LukeSmithxyz/st#136]
`X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  63
  Current serial number in output stream:  64
`
is what I get whenever I try to use dmenu -w "$WINDOWID" with this fork, any way to fix ?

**Comment by mbauhardt** [comment]
I have the same issue and I'm also very interested into an answer.

**Comment by LukeSmithxyz** [comment]
Closing this. Yes the transparency is the issue, and you'll have to patch dmenu with an alpha patch too. You can use [my dmenu build](https://github.com/LukeSmithxyz/dmenu) which I just added the patch into. I think the one on suckless's site isn't really working without changes.
