### ISSUE TITLE
Copy from mouse selection

### ISSUE THREAD

**Issue by jscolaire** [LukeSmithxyz/st#137]
Great build.
I use your build for st with a few changes, minimal changes. I try paste from selection mouse but it doesn't work if not previous copy through Ctrl+C; selection mouse in browser for example. If selection is inside st it works (selection with mouse and paste).

Usually I select from mouse and whithout Ctrl-+C I paste with central button of mouse. How do I make this change.

Thanks,

**Comment by guvolinux** [comment]
Hi ! maybe I should check ... https://git.suckless.org/st/

**Comment by LukeSmithxyz** [comment]
I had fixed this a couple weeks ago now.

**Comment by jscolaire** [comment]
Thanks

José Antonio
