### ISSUE TITLE
Font ligatures in the "st" terminal emulator?

### ISSUE THREAD

**Issue by igorlakic** [LukeSmithxyz/st#139]
I have one question about the "st" terminal emulator. I know that you don't work on "st" development but I thought that this is the best place for a such question.

Is it possible to enable font ligatures in the "st"? And if it's possible, how to accomplish that?

Thanks in advance,
Iggy

**Comment by glpzzz** [comment]
> Is it possible to enable font ligatures in the "st"?

 as far as I know there is no  patch for it yet

**Comment by igorlakic** [comment]
> > Is it possible to enable font ligatures in the "st"?
> 
> as far as I know there is no patch for it yet

Too bad. That would be a really nice feature...

**Comment by LukeSmithxyz** [comment]
I don't have intentions of adding this myself. If someone comes up with a patch, I wouldn't be against it, but it's not something of big concern to me.

**Comment by glpzzz** [comment]
Yes, I can leave without it. But font ligatures are beautiful! Monoid and Fira Code are very good examples.

**Comment by magnusmb** [comment]
@cog1to has made a patch for ligatures, using Harfbuzz.
https://st.suckless.org/patches/ligatures/

**Comment by LukeSmithxyz** [comment]
I was sort of hoping this would fix multicharacter emojis too, but it just does something funky with them. I suppose that's an improvement though... I'll play around with it and might add it.

![pic-full-200416-1216-23](https://user-images.githubusercontent.com/29150857/79480616-55f6ed00-7fdc-11ea-97c4-068ca4d50df8.png)

**Comment by cog1to** [comment]
Can someone post a sample of a multi-character emoji here?

The patch wasn't made for those in mind, and I'm not sure if Harfbuzz supports them either, but I'm willing to check. If it's not too hard to fix, I may include it in my patches.

**Comment by LukeSmithxyz** [comment]
Reopening this. I might add the suckless patch, but I'd really like the issue above to be dealt with additionally.

**Comment by mackarelfish** [comment]
Added the feature on [#206](https://github.com/LukeSmithxyz/st/pull/206).
