### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by PittacusOfLorien** [LukeSmithxyz/st#14]
Compiles normally on the latest arch, but when I try to run it it says
`free(): invalid next size (normal)`

**Comment by tiga16** [comment]
I am having the same Issue, how did you solve it?

**Comment by PittacusOfLorien** [comment]
Sorry, I forgot to say. It was a font error. You should be able to fix it by modifying the config.h

**Comment by tiga16** [comment]
Thank you! Setting autohint to false solved it.
