### ISSUE TITLE
st terminal is seriously broken

### ISSUE THREAD

**Issue by m-kru** [LukeSmithxyz/st#141]
st terminal is seriously broken. If you like `CTRL+z` + `fg` workflow forget about st as you can expect this all the time (stdout gets mixed with vim buffers after `CTRL+z`):
![st_bug](https://user-images.githubusercontent.com/26227737/69267444-7194cd80-0bcd-11ea-9dfd-9f7c32890249.png)

**Comment by LukeSmithxyz** [comment]
I can't replicate this problem.

**Comment by m-kru** [comment]
I also do not know how to replicate this, it looks like it is non deterministic, it just sometimes happens on my machine.
