### ISSUE TITLE
can your st support BiDi

### ISSUE THREAD

**Issue by Monirzadeh** [LukeSmithxyz/st#144]
hi
it is possible to add  BiDirectional text support into st ?
for now bellow text show as separate alphabet in st
نوشتار فارسی
show somethings like this
![Screanshot-2019-12-06-01-45-07-699111607](https://user-images.githubusercontent.com/25131576/70278810-377d1b80-17ca-11ea-90b9-865aeba95db5.png)

**Comment by LukeSmithxyz** [comment]
No, there is no patch for this.
