### ISSUE TITLE
Garbage on the terminal

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/st#147]
I have used the .Xdefaults file that is on the repository. Every time I use **man** or **less**, I end up with garbage on the output. This is a problem on any cli application as well, I just used **man** as an example.

```bash
kcc@foo: ~ man man
MAN(1)                                         Manual pager utils

[1;36mNAME[0m
       man - an interface to the system reference manuals

[1;36mSYNOPSIS[0m
       [1;36mman[0m [[1;32mman[0m [1;32moptions[0m] [[[1;32msection[0m] [1;3
       [1;36mman[0m [1;36m-k[0m [[1;32mapropos[0m [1;32moptions[0m] [1;32mre
       [1;36mman[0m [1;36m-K[0m [[1;32mman[0m [1;32moptions[0m] [[1;32msecti







MAN(1)                                         Manual pager utils

[1;36mNAME[0m
       man - an interface to the system reference manuals

[1;36mSYNOPSIS[0m
       [1;36mman[0m [[1;32mman[0m [1;32moptions[0m] [[[1;32msection[0m] [1;3
       [1;36mman[0m [1;36m-k[0m [[1;32mapropos[0m [1;32moptions[0m] [1;32mre
       [1;36mman[0m [1;36m-K[0m [[1;32mman[0m [1;32moptions[0m] [[1;32msecti
```

I am sure there is some file that I have either munged or removed... What is the trick to getting that back to normal?

**Comment by rootl0rd** [comment]
What locale are you using? I’ve had problems with certain eye candy programs that don’t display certain characters because of locale... and only en_US seems to work (despite trying en_AU). 
I’d recommend reading this:
https://wiki.archlinux.org/index.php/locale

**Comment by kcallis** [comment]
Thanks @tokumei27! I happened to run across your email where is seemed to get lost. I happened to see @LukeSmithxyz  videos and thought maybe I should just clone his code and re-build. Now I would like to believe that I had did a make initially, but when I went to do a make, it would seem that some of X libraries where not installed. 

I do enjoy Luke's larbs, but at times, I wish I could just remove LARBS and get a fresh you re-installed. It seems like everything is falling apart.

**Comment by tokumei27** [comment]
Well if you had errors when making it, then that probably explains it. If you think it’s a missing X library (I would be surprised) then I will suggest a fix...

Since LARBS installs the bare minimum Xorg packages, it’s advisable to install the rest of the Xorg packages. On arch, there is a package group called xorg that contains all you will need. 

Install xorg package group:
`sudo pacman -S xorg`
Then reclone Luke’s st clone and `cd` into the folder.
Then make clean:
`sudo make clean install`


Hope this helps. I didn’t really understand your comment.

**Comment by kcallis** [comment]
I installed xorg (for some reason, I thought I had previously, but it might have been missed). I am still getting the same garbage. I am wondering if I am missing a font or something wrong with my .Xresources.
