### ISSUE TITLE
Vim colorscheme doesn't work

### ISSUE THREAD

**Issue by FilipLitwora** [LukeSmithxyz/st#148]
I'm really sorry if this is a noob question, but i've recently switched to st and i have one problem.
I dont get any colors in vim with any colorscheme, just white text...
This doesnt happen in othe terminal emulators like konsole.
I didn't change anything in `config.h`

**Comment by shahzebs** [comment]
I got my colorscheme back when I commented out `set termguicolors`. Maybe try that?
