### ISSUE TITLE
Weird Issue on St when using  with xdotools

### ISSUE THREAD

**Issue by goldcoders** [LukeSmithxyz/st#149]
I have rofi installed on my laptop , as well as rofi-pass

for some reason only when im using rofi-pass to type my username and password it freeze

and hangs up, 

Ive tested this with a stterm ( st -distibuted by ubuntu ) like a plain st without patches

Ive also tested this with ubuntu terminal gnome terminal

those 2 teminals can easily type very fast with xdotools with rofi-pass default

As you can see i have a video here where Im using it with ST by @LukeSmithxyz 

https://www.youtube.com/watch?v=w0tsiGt6mIw&feature=youtu.be

i have no other options left but to reduces the delay from 2ms on keyword and 20ms on key type to 100ms both, just to avoid freezing in the middle of typing password

This is veryslow typing, and i have no other solution 

Im posting here because the issue is only showing up in this St build.

If anyone can offer a more brilliant solution please tell me

**Comment by setanta** [comment]
I was having the same problem, and doing some digging find out that it all started on [3cd9189](https://github.com/LukeSmithxyz/st/commit/3cd91894ec91a0de7aa71d62949ba3381e600afd) _"Updated st to 0.8.2"_, and it was something related to key releases.

I did the following and rofi-pass worked once again.

```
diff --git a/x.c b/x.c
index c09392b..e819aa4 100644
--- a/x.c
+++ b/x.c
@@ -1230,7 +1230,7 @@ xinit(int cols, int rows)
 	xw.attrs.background_pixel = dc.col[defaultbg].pixel;
 	xw.attrs.border_pixel = dc.col[defaultbg].pixel;
 	xw.attrs.bit_gravity = NorthWestGravity;
-	xw.attrs.event_mask = FocusChangeMask | KeyPressMask | KeyReleaseMask
+	xw.attrs.event_mask = FocusChangeMask | KeyPressMask
 		| ExposureMask | VisibilityChangeMask | StructureNotifyMask
 		| ButtonMotionMask | ButtonPressMask | ButtonReleaseMask;
 	xw.attrs.colormap = xw.cmap;
```

I've checked https://st.suckless.org/ and the `KeyReleaseMask` was introduced on commit e85b6b6 _"better Input Method Editor (IME) support"_. My digging didn't go any further than that, and probably there's a better way to fix this problem, but at the moment I'll run with just removing `KeyReleaseMask`.
