### ISSUE TITLE
Some shortcuts don't work

### ISSUE THREAD

**Issue by infiltratorXYZ** [LukeSmithxyz/st#152]
I've been using st for some (long) time and I've never had a problem with it. But now zooming hasn't worked for a few days. I tried to solve this problem in several ways (including reinstalling st and installing previous versions), but it doesn't work.

Looking for a solution, I noticed that the zoom mechanics work quite well (when I changed the shortcuts to Alt+j/k), so the problem must be related to the correct reading of the shift key when it is used with another modifier (uppercase letters and single 'ShiftMask' also works).

Maybe someone had similar problem and managed to solve it?

**Comment by LukeSmithxyz** [comment]
Have you possibly bound that same sequence as a global key binding in
another program? I have not had such a problem and there hasn't been an
update to this build in a while.

**Comment by infiltratorXYZ** [comment]
I don't think so. I've never used Alt+Shift+(...) shortcuts outside the terminal. But I play with system and configuration a lot, so probably I screwed up something.

I'm going to look into this problem in a while. Maybe I'll find a solution. So far the Alt+h/l keys for zooming are pretty well for me. 

If I find something, I'll post here.

By the way, I think your work on this build is very reasonable. It's very comfy configuration. I really appreciate it every day.

**Comment by rootl0rd** [comment]
Do you use Luke’s rice / LARBS?
If so I’d check the `sxhkd` config at `~/.config/sxhkd/sxhkdrc`

**Comment by kevin-weiss** [comment]
I had the same problem and it was due to the sxhkd binding for moving floating windows, which is in the default config, I think. Deleted it, reloaded sxhkd and zooming works like a charm.

```bash
# Move floating windows
alt + shift + {h,j,k,l}
       bspc node -v {-20 0,0 20,0 -20,20 0}
```
