### ISSUE TITLE
color emoji?

### ISSUE THREAD

**Issue by goldcoders** [LukeSmithxyz/st#159]
I tried installing the patch of libxft-bgra
and remove the font config for fallback for ttf-symbola

but still i dont see colored emoji in ST or dmenu...

i also did fc-cache -fv 

after that still no colored emoji...

Did you do something in ST to avoid this from happing
@LukeSmithxyz 

Can you pinpoint the correct file and line to change?

thanks

**Comment by olekhov** [comment]
I've removed ttf-symbola (AUR repository points out to  http://users.teilar.gr/~g1951d their site says they will not release new fonts until March 13, 2020, when new unicode is approved) and noto-fonts-emoji.

I've installed ttf-apple-emoji and it semi-worked.

![image](https://user-images.githubusercontent.com/2698890/73919956-9861c680-48d5-11ea-9bdc-524b22708f18.png)

Need to check /etc/fontconfig/conf.d dir as well as ~/.config/fontconfig/fonts.conf

**Comment by LukeSmithxyz** [comment]
Between your fontconfig and your st build, you need to set a color emoji font as default. The build has now been updated to look for JoyPixels as a default fallback font.
