### ISSUE TITLE
Primary clipboard / pasting broken

### ISSUE THREAD

**Issue by anonaii** [LukeSmithxyz/st#16]
OS: Kubuntu 18.04.1 LTS
Version of st: latest

When I paste, it doesn't paste anything at all, pasting my primary clipboard works in other applications (and urxvt) but not in st. Now if I select some text in st and try to paste it will past that text perfectly fine, but if I close the current st and open up a new one then it won't paste the previously selected text.

**Comment by LukeSmithxyz** [comment]
I've made an update (to the man as well) which clarifies some of copy/pasting shortcuts. There was a period where the bindings weren't properly reflected in the manual, so you may've been pressing the wrong keys. Now it's:

- `alt-c` for copy
- `alt-v` or `shift-insert` for paste
- `alt-p` to input primary selection

I will say that the fact that your pasting is non-persistent after you close a window is a general property of X See the answer to this for example: https://unix.stackexchange.com/questions/450508/how-to-keep-clipboard-content-from-xterm-after-closing-it-like-firefox-or-le

There are probably ways of bypassing this problem and I'm sure you could look it up, but it's not a aspect specific to this program.
