### ISSUE TITLE
Alt+L URL interpreter breaks Mastodon links (URLs containing "@")

### ISSUE THREAD

**Issue by sawyer07** [LukeSmithxyz/st#160]
Unlike Twitter, Mastodon links contain actual "@" signs in front of user names. An email with several mastodon links for example
```
https://mastodon.social/@diggity
https://mastodon.social/@privacylab
https://mastodon.social/@privacysafe
```
will yield only 
`https://mastodon.social/`
as a possible link to navigate to

**Comment by LukeSmithxyz** [comment]
Added.
