### ISSUE TITLE
Reverse search in history

### ISSUE THREAD

**Issue by yassersouri** [LukeSmithxyz/st#161]
Is there a reserve search in history feature? I tried looking around and couldn't find anything.

**Comment by shahzebs** [comment]
I believe bash has this built in as CTRL + R

**Comment by yassersouri** [comment]
CTRL + R does nothing on my machine. BTW my machine is arch + larbs and
nothing else.

Do you know how should I diagnose the problem?

**Comment by LukeSmithxyz** [comment]
LARBS uses vi mode in the shell. Check the documentation for that. It's not related at all to st.
