### ISSUE TITLE
Crash opening a shell file

### ISSUE THREAD

**Issue by Neules** [LukeSmithxyz/st#162]
While opening a shell file like `dmenumount` I get `st` crash, causing `st` window disappear. It shows the content of the file just 1 milisecond after it crashes. I can edit other files (rmarkdown, plain text) successfully (no window crash).
**note**: It's not exactly _your_ `dmenumount` , it's a custom one.

- Tried with `konsole`, `kitty`, even `kate` and not showing that behaviour (I can open and edit the file on those). 
- I've tried different editors also (`vim`, `nvim`, `nano`) on `st` and I get same crash nevertheless.

Can an error on that shell file cause a `st` crash? How can I debug `st` so I can see what's happening before `st` crashes?

- `dmenumount` is executable.

**Comment by LukeSmithxyz** [comment]
It's the emoji crash. Install libxft-bgra.
