### ISSUE TITLE
Transparency not persistent after xrdb

### ISSUE THREAD

**Issue by shahzebs** [LukeSmithxyz/st#163]
I tried to change the transparency of st by adjusting the alpha value in .Xdefaults. When I run `xrdb .Xdefaults`, and launch a new terminal, the transparency does change. However, when I restart dwm (or X), the transparency returns to the previous value, i.e. the change isn't persistent. 

I have very little experience with Xresources, and I don't think I have created any other resources files than .Xdefaults shipped with this st build.  I haven't used Pywal either. 

Any ideas?

**Comment by LukeSmithxyz** [comment]
Yes, this is a known issue. It used to be worse... the colors of old
terminals used to go wild as well. I'm not sure right now how to solve
it at the moment.

**Comment by shahzebs** [comment]
Is the norm to run `xrdb .Xresources` on boot? Or is it supposed to be persistent? 
I remember last time I changed the alpha value the change was in fact persistent.

**Comment by tokumei27** [comment]
For now, comment out your alpha variable in the `.Xresources` File, and use the alpha variable in your st clone and rebuild.

**Comment by LukeSmithxyz** [comment]
> Is the norm to run `xrdb .Xresources` on boot? Or is it supposed to be persistent?
> I remember last time I changed the alpha value the change was in fact persistent.

xrdb settings are never persistent unless you make them persistent with `xrdb`, or by putting them into `.Xdefaults`.
