### ISSUE TITLE
Can't adjust the thinkness of characters

### ISSUE THREAD

**Issue by BinhKhang** [LukeSmithxyz/st#166]
I read your README.md file and tried to change the values in config.h file thoroughly, but I can not change the thickness of characters.
Do you have any idea?

**Comment by LukeSmithxyz** [comment]
What do you mean by "thickness?"

**Comment by BinhKhang** [comment]
What I meant are **bolder** characters, instead of normal ones, which are quite thin (to me).

**Comment by LukeSmithxyz** [comment]
I mean you might just want to use another monospace font as default then. My build is just reading your system default mono font.

**Comment by BinhKhang** [comment]
Got it. Thank you very much.
Can I ask one more question within this thread?
-How can I adjust colors as in your terminal emulator (in your Youtube vids): yellow for username, red for computer's name, etc.?

**Comment by LukeSmithxyz** [comment]
That's not related to a terminal emulator"

See: https://www.youtube.com/watch?v=hMSByvFHOro 😉

Change your `$PS1`.

**Comment by BinhKhang** [comment]
Well, I finished it. It is interesting.
Thank you very much. 😁
