### ISSUE TITLE
Can not make terminal window transparent.

### ISSUE THREAD

**Issue by BinhKhang** [LukeSmithxyz/st#167]
I changed the value of _alpha_ (opacity) in file _config.h_ but it increases or decreases the intensity of the terminal window only; however, it doesn't make the terminal window transparent to see the wallpaper.
Do you have any idea?

**Comment by LukeSmithxyz** [comment]
Do you have a composite manager running like xcompmgr?

**Comment by BinhKhang** [comment]
I've just installed it. What steps do I do next?

**Comment by LukeSmithxyz** [comment]
Run it...

**Comment by BinhKhang** [comment]
Hmm, it seems that st doesn't work well with xcompmgr.
I get this error a lot: 
**error 140: BadRegion request 138 minor 14 serial 1335**

**Comment by Rushmore75** [comment]
Are you using awesomewm?
https://wiki.archlinux.org/title/Xcompmgr#BadPicture_request_in_awesome
