### ISSUE TITLE
compile error on fresh arch install 

### ISSUE THREAD

**Issue by smikeblog** [LukeSmithxyz/st#168]
usr/bin/ld: st.o: in function `draw':
st.c:(.text+0x3236): undefined reference to `ximspot_update_interval'
collect2: error: ld returned 1 exit status
make: *** [Makefile:30: st] Error 1

**Comment by FilipLitwora** [comment]
Same issue here. Did you fix it ?

**Comment by smikeblog** [comment]
No! I patched myself st and copied keybinding from Luke's st. I describe the procedure and patched sources are here https://github.com/smikeblog/st-smike

**Comment by LukeSmithxyz** [comment]
I would think that https://github.com/LukeSmithxyz/st/commit/6725a2fde0127694176901ebf6217024b832fd8e is the origin of the build issue here, but that would mean you're missing some basic build files on your machine. I think that `time.h` is a basic part of `glibc` on Arch...

**Comment by FilipLitwora** [comment]
I figured out why it didn't compile but forgot to comment and close... I was using old config for on the newest commit
