### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by saifulapm** [LukeSmithxyz/st#17]
Hello,

How can I change default font ? Is this possible ? I am using Larbs setup. Please help me.

Thanks

**Comment by saifulapm** [comment]
I got it. Just need to rebuild with proper config.h 

Thanks for awesome build

**Comment by minikN** [comment]
Just to note, you don't need to rebuild in order to change the font. You can run st with

`st -f 'Inconsolata:size=8'`. Replace font name and size with desired combination. That's it.
