### ISSUE TITLE
Emoji flags

### ISSUE THREAD

**Issue by omaranbari** [LukeSmithxyz/st#170]
This isn't necessarily a ST issue but I was wondering if anybody had issues rendering flags.
When I copy and try to paste a flag, I get the two-letter code instead of the flag picture.
When I paste it into a browser or libreoffice, I don't see the same problem.
Thank you

**Comment by LukeSmithxyz** [comment]
This is the same with any other multi-character emoji. I don't know if it's something with libxft or st, etc. at this point.

**Comment by VineshReddy** [comment]
I don't have any issue with rendering coloured flags. can you specify with flag emoji you get issue.
