### ISSUE TITLE
ranger image previews do not work

### ISSUE THREAD

**Issue by msoulier** [LukeSmithxyz/st#179]
Sorry if I'm missed something obvious but I just grabbed your latest source and built on Debian buster, and ranger image previews don't work. They do work in xterm and urxvt. 

Ranger version 1.9.2-4 in Buster.

**Comment by LukeSmithxyz** [comment]
Are you using w3m or ueberzug to render them? I'll go ahead and say that w3m image previews are, I hate to use the word, deprecated and they don't and will never work with this terminal build. Ueberzug should work well in ranger though.

**Comment by msoulier** [comment]
On 01/04/20 Luke Smith said:

> Are you using w3m or ueberzug to render them? I'll go ahead and say
> that w3m image previews are, I hate to use the word, deprecated and
> they don't and will never work with this terminal build. Ueberzug
> should work well in ranger though.

Yeah, w3m. I was unaware of the ueberzug method. Looking into it, it
might be a little too bleeding edge for my Debian Buster box. 

Thanks,
Mike

**Comment by LukeSmithxyz** [comment]
Okay. I don't plan on bothering with w3m images. I hate to use the word "deprecated," but they're basically deprecated. I think ueberzug and possibly the ikitty renderers are possible, but I guess on Debian you might have to wait for that...
