### ISSUE TITLE
ncmpcpp visuals not working

### ISSUE THREAD

**Issue by narukeh** [LukeSmithxyz/st#181]
At first ncmpcpp gave me an error when i tried to go to wave vis: [ Could't open "/tmp/mpd.fifo" for reading PCM data: No such file or directory ]
so i simply: "touch /tmp/mpd.fifo" and restarted st but it still wouldn't work.
So i went to tty2 and launched ncmpcpp, there the visuals worked.
Just to test i installed 'xterm' , and there the ncmpcpp's visual mode also worked.
which means it is a st bug?

**Comment by LukeSmithxyz** [comment]
Changte your font in st. See if that changes it.

**Comment by narukeh** [comment]
I changed the font in st's confi.h but that made no diff
the problem was the emoji fonts in the monospace section of ~/.config/fontconfig/fonts.conf
i removed it all and then it worked. now it looks like this:
`<alias>
		<family>monospace</family>
		<prefer>
			<family>Ubuntu Mono</family>
		</prefer>
	</alias>`

**Comment by LukeSmithxyz** [comment]
Okay, interesting. I'll see if I can't fix this for good. It looks like
it's interfering with some East Asian fonts as well.
