### ISSUE TITLE
Background color not updating after changing wallpaper and loading wal

### ISSUE THREAD

**Issue by ekollof** [LukeSmithxyz/st#182]
When updating the colorscheme with pywal, the st background doesn't get updated. Shell colors change fine, but not the st background. I suspect it's sequence related (where wal uses a color code for backgrounds the st terminal doesn't).

I've tried hacking st in a few places, googling, but nothing's really conclusive. Hoping more eyes will see this and make this bug shallow.

Possibly related issues/regressions: #142

Screenshot of problem in action: 

![Screenshot of problem in action](http://0x0.st/iMjb.png)

**Comment by trissim** [comment]
This has been fixed
