### ISSUE TITLE
Mouse wheel pasting text

### ISSUE THREAD

**Issue by Fogapod** [LukeSmithxyz/st#184]
There is a weird issue with mouse wheel.
### Steps to reproduce
* Open new terminal window
* Copy text to clipboard (from anywhere)
* Scroll mouse wheel up (nothing happens)
* Paste text to terminal
* Scroll mouse wheel up (now it pastes text on every  scroll event)
* Copy other text to clipboard
* Scroll mouse wheel up (old text getting pasted until you paste new one into terminal)

![image](https://user-images.githubusercontent.com/22667809/78139806-bc530b80-7431-11ea-9a6b-10271cd6b012.png)

**Comment by LukeSmithxyz** [comment]
Middle click pastes from selection again after very recent commits now.

To scroll in the terminal, hold alt or shift. Otherwise you will be inputing termschars that correspond to pasting in your shell.
