### ISSUE TITLE
copying text without using mouse?

### ISSUE THREAD

**Issue by thepenguinthatwants** [LukeSmithxyz/st#186]
Hi!

I've being using tmux but noticed that copy mode doesnt copy as much as I expected.

And using mouse and  alt-c being working better. Wondering if its possible to navigate in the terminal and copy text without moving mouse?

**Comment by LukeSmithxyz** [comment]
There's an st patch for manually navigating, but I haven't added it. If you use tmux, you should be using copying feature in that. I'm not going to code around multiplexer programs.
