### ISSUE TITLE
pipes and other characters don;t show in terminal based apps

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/st#187]
pipes & squares that are used for example in pulsemixer as a volume bar don't show up in console output of this build of st

comparison lukesmith st and kitty
[lukesmith st](https://0x0.st/iuMM.png)
[kitty](https://0x0.st/iuMu.png)

while both use the same font

**Comment by LukeSmithxyz** [comment]
I've never been able to duplicate this. There's another issue on this in one of my other repos.

**Comment by kronikpillow** [comment]
your latest commit seems to have fixed it
