### ISSUE TITLE
Script - Not working with Debian base :(

### ISSUE THREAD

**Issue by dlj2019** [LukeSmithxyz/st#188]
Script _Error ...

c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.2\" -D_XOPEN_SOURCE=600  -O -c x.c
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
x.c:11:10: fatal error: X11/Xatom.h: No such file or directory
   11 | #include <X11/Xatom.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22: x.o] Error 1

----------------------------------------------------------
Can i get any help !?

**Comment by LukeSmithxyz** [comment]
Install the build dependencies required. The error message tells you.
