### ISSUE TITLE
Mouse whell issue with Majaro (Under VirtualBox 6.1.4)

### ISSUE THREAD

**Issue by hww** [LukeSmithxyz/st#192]
Hello,

Scrolling mouse whell up - print characters ^Y
Scrolling down - starts vim with file name /tmp/zshbvEogN

My system: Manjaro XFCE 19.0.2 under Virtual Box 6.1.4, plus LARBS, ST runs in i3 session

**Comment by LukeSmithxyz** [comment]
Hold shift or alt to scroll.

**Comment by Applepi** [comment]
What is the intended use of those normally? I'm trying to break the habit but it would be nice to know the underlying cause.
