### ISSUE TITLE
Neofetch display image

### ISSUE THREAD

**Issue by kevariable** [LukeSmithxyz/st#198]
Running with Arch Linux and bspwm
with st, so I have tried anything but it's doesn't work with me

**Comment by LukeSmithxyz** [comment]
st doesn't support w3m images. While I believe this build is already compatible with ueberzug images, I have no intention of supporting w3m since it's effectively deprecated and inferior. I'm not sure if neofetch supports ueberzug, but you might ask the maintainer of that project.
