### ISSUE TITLE
Release the updated externalpipe patch as a diff

### ISSUE THREAD

**Issue by AtomToast** [LukeSmithxyz/st#199]
I really enjoy the feature of externalpipe working on the entire history, instead of just the current screen. However I don't want all of the other features and rather maintain my own build of st.

I tried figuring out what parts of your config belong to the patch but it was quite a hassle and I eventually gave up with all the unrelated diffs I had to sort out.

Would it be possible for you to release your work as an official, updated patch? It would be greatly appreciated!

**Comment by LukeSmithxyz** [comment]
What do you mean by "an official, updated patch?"

**Comment by AtomToast** [comment]
What I meant was that ideally, it would be added onto the official suckless page. Maybe as an updated version of the current externalpipe patch.

In my opinion it's a great change and more people should be able to benefit from your work

**Comment by LukeSmithxyz** [comment]
Well the commit was da13ef12463d1870caed94584db464d68c6b3182, so just run `git format-patch -1 da13ef12463d1870caed94584db464d68c6b3182` and there you have it.

**Comment by AtomToast** [comment]
Not exactly what I was looking for but this works for me, I appreciate it!

**Comment by AtomToast** [comment]
I now have made the diff work on a minimal st build with only externalpipe and scrollback installed and published it here https://st.suckless.org/patches/externalpipe/

I gave you credit in the diff file
