### ISSUE TITLE
I can't resize the font

### ISSUE THREAD

**Issue by klorophatu** [LukeSmithxyz/st#20]
Doing `Shift+Alt+PageUp/PageDown` does not increase or decrease the font, instead it scrolls up or down
How do I fix that?

**Comment by LukeSmithxyz** [comment]
Well you're either not holding down shift properly or using an old build. I just retested the most recent build and the font resize bindings work fine.

**Comment by klorophatu** [comment]
> Are you using any unique keyboard layout? What is your system's default mono font?

Fixed it, the problem was on /etc/X11/xorg.conf.d/00-keyboard.conf in XkbOptions, the alt shift switch layout thing
You probably set something to disable that with some of your scripts or something
