### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/st#200]
tic -sx st.info
"st.info", line 192, col 11, terminal 'st': expected string-type for Se, have boolean
"st.info", line 193, col 11, terminal 'st': expected string-type for Ss, have boolean
4 entries written to /etc/terminfo

- Full output:
[a@Dwm ~/st]$ sudo make clean install
rm -f st st.o x.o st-0.8.2.tar.gz *.orig *.rej
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.2\" -D_XOPEN_SOURCE=600  -O -c st.c
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.2\" -D_XOPEN_SOURCE=600  -O -c x.c
c99 -o st st.o x.o -L/usr/X11R6/lib -lm -lrt -lX11 -lutil -lXft -lXrender  `pkg-config --libs fontconfig`  `pkg-config --libs freetype2`
mkdir -p /usr/local/bin
cp -f st /usr/local/bin
cp -f st-copyout /usr/local/bin
cp -f st-urlhandler /usr/local/bin
chmod 755 /usr/local/bin/st
chmod 755 /usr/local/bin/st-copyout
chmod 755 /usr/local/bin/st-urlhandler
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/0.8.2/g" < st.1 > /usr/local/share/man/man1/st.1
chmod 644 /usr/local/share/man/man1/st.1
tic -sx st.info
"st.info", line 192, col 11, terminal 'st': expected string-type for Se, have boolean
"st.info", line 193, col 11, terminal 'st': expected string-type for Ss, have boolean
4 entries written to /etc/terminfo
Please see the README file regarding the terminfo entry of st.
[a@Dwm ~/st]$

**Comment by LukeSmithxyz** [comment]
Fixed in fdf3989005a9003b90a3e98d4ba5684d52f11d3c. Should've been non-fatal anyway.
