### ISSUE TITLE
Error when re-attaching to a tmux session

### ISSUE THREAD

**Issue by pierg75** [LukeSmithxyz/st#201]
Not entirely sure how I got into this, but I think I accidentally close the terminal with tmux. Once I tried to open a new terminal and connecting to the tmux session the terminal would crash.
Starting the terminal manually I got:

X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  138 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  3064
  Current serial number in output stream:  3519

Not even sure this is a terminal issue TBH.
Distro is Fedora 32.

**Comment by LukeSmithxyz** [comment]
Install libxf-bgra.
