### ISSUE TITLE
Launching st and specifying name

### ISSUE THREAD

**Issue by BigfootN** [LukeSmithxyz/st#202]
Hello,

I am trying to launch `st` with the `-n` option. To be more specific: `st -n <somename> -e nvim` and here is the result:

![2020-05-04-110649_903x954_scrot](https://user-images.githubusercontent.com/1183923/80951061-66d69980-8df7-11ea-814b-af3cf3414958.png)

I don't have any problem without specifying the name. I would also like to add that the font is not the right one, the one specified in my `Xresources`.

I don't know if it's relevant to the problem, but I have this message when executing the command:

```
erresc: unknown csi ESC[22;0;0t
erresc: unknown csi ESC]11
```
I also tested with the "official" `st` and I didn't face any problem when specifying the name (`-n`). 

Thank you very much in advance for your help.

**Comment by LukeSmithxyz** [comment]
Does this happen with any other tui programs? It might be some vim plugin interacting with st. I don't have any issue like this with nvim.

**Comment by BigfootN** [comment]
Thank you for your quick response. I think I found the problem. In my `init.vim` config, I had the [gruvbox plugin](https://github.com/morhetz/gruvbox) and the [airline plugin](https://github.com/vim-airline/vim-airline). When disabling them **both**, not juste one, the problem is resolved. For the moment I am unable to see the source of the problem.

Thank you very much for your help.

**Comment by LukeSmithxyz** [comment]
Okay. I'm going to close this issue. Yeah, vim plugins interact in very strange ways I find. I have a couple of glitches due to them.

**Comment by BigfootN** [comment]
Thank you for your time and help.
