### ISSUE TITLE
Graphical windows launched in termnial get placed on top of terminal

### ISSUE THREAD

**Issue by AlexBocken** [LukeSmithxyz/st#203]
I've noticed that with a recent update of mine to one of the newer versions of Luke's build graphical applications launched in st don't spawn a new window but just sit atop of st.
 I personally don't like this since if I'm launching an application via the terminal i'll most likely be interested in it's stdout and stderr while running it.

Is there a way to reverse this change? In what file or even function do I have to look?
I looked a bit around in the code but couldn't find anything that would lead me in the right direction.
The commits over the last few months also don't say anything about this feature.

**Comment by LukeSmithxyz** [comment]
Just launch it prefixed with `setsid`.

This is the swallow patch to dwm, for your information.

**Comment by AlexBocken** [comment]
Ah, I think that was completely on my side then, my apologies for bothering.

Thank you very much for your help!
