### ISSUE TITLE
st crashes whenever i run ps_mem command

### ISSUE THREAD

**Issue by shubham-cpp** [LukeSmithxyz/st#204]
it gives this error
` X Error of failed request:  BadLength (poly request too large or internal Xlib length error) `

- Major opcode of failed request:  139 (RENDER)
- Minor opcode of failed request:  20 (RenderAddGlyphs)
- Serial number of failed request:  2331
- Current serial number in output stream:  2363

to be more precise when i run this command 
`sudo ps_mem | sort -h -k 1n`

If I remove the sort function it will work, but if I add sort, then it crashes for some **BadLength** reason

**Comment by LukeSmithxyz** [comment]
Install `libxft-bgra`.

**Comment by shubham-cpp** [comment]
Hello luke, I've using your st build for a week now, but I have encountered
a problem with delete key. For my vim I use ctrl + del (in insert mode) to
perform D operation(of normal mode) But in this st build it doesn't work. I
commented out the keys that were interfering with my key binding, but it's
still not working
