### ISSUE TITLE
something like the 'vim browse' or 'keyboard select' patch?

### ISSUE THREAD

**Issue by GasparVardanyan** [LukeSmithxyz/st#207]
Or it's better to do something using externalpipe and vim.
I've done something like that in my fork of st: https://github.com/GasparVardanyan/st/blob/master/config.h#L229

**Comment by LordRusk** [comment]
I have vimbrowse in my st build, its great, removes any need for the mouse while using the terminal and can perform actions like `yi[` and it will yank inside square brackets. I would recommend this patch 100%.

**Comment by GasparVardanyan** [comment]
vim-browse doesn't support regex search ((
The biggest advantage of urxvt over st is that urxvt has a prel interpreter I think.

**Comment by GasparVardanyan** [comment]
Now seems it works fine in my fork: https://github.com/GasparVardanyan/st/commit/418f06c79262530a534e068f620fd15984a1c0ba

**Comment by dapc11** [comment]
Which version of vim-browse to apply in luke's ST fork?

**Comment by GasparVardanyan** [comment]
vim-browse includes the scrollbach patch.
Try first to unpatch the applied version of the scrollback patch with **patch -R**, then apply the latest version of the vim-browse patch.

**Comment by Cyberdr3am** [comment]
I try to add vim-browse to the actual luke build of st because it's just awesome ( i don't know why luke don't use it )
After apply the patch i have some problem and i don't know how to fix it.
If somebody have a fork of luke st with vim browse it would be awesome.

**Comment by LukeSmithxyz** [comment]
I'm warming to the idea of this patch and might add it soon.

**Comment by Cyberdr3am** [comment]
vim browse is just awesome. I don't know why you don't add this before.

**Comment by lucas-mior** [comment]
> Now seems it works fine in my fork: [GasparVardanyan/st@418f06c](https://github.com/GasparVardanyan/st/commit/418f06c79262530a534e068f620fd15984a1c0ba)

That's better than vim-browse, because its more flexible.

**Comment by lucas-mior** [comment]
See #287

**Comment by CT-66** [comment]
Hey Luke, has the patch been applied? Looks like the issue has been closed.
