### ISSUE TITLE
Customize keybindings

### ISSUE THREAD

**Issue by enanajmain** [LukeSmithxyz/st#21]
I have started to maintain my own fork of the official git repo. The one problem I keep getting on is to customize keybindings. I guess I edit the `config.h` file, but I don't understand which keys are what. For example, how did you get `Alt`+`j/k` to scroll up and down?

**Comment by LukeSmithxyz** [comment]
The keybinds are defined in `static Shortcut shortcuts[]` while the `MODKEY` is defined as Alt (`Mod1Mask`) on the line `#define MODKEY Mod1Mask`.

**Comment by enanajmain** [comment]
But what are the purposes of the column `argument`?

**Comment by LukeSmithxyz** [comment]
Well, it depends on the function called. You can check each individual function yourself. For example, `zoom` can take an argument that will determine whether it zooms in or out. You have the source code and can look for yourself, although if you just want to rebind keys, you can probably just intuit it just looking at the shortcuts there.

**Comment by enanajmain** [comment]
Oh, Thank you. I should've guessed those are functions and the arguments are parameters for them. Slips on the first time.
