### ISSUE TITLE
Shift + Insert not pasting

### ISSUE THREAD

**Issue by cantao** [LukeSmithxyz/st#213]
Hi!

If I am not wrong, the following line (258 on config.h) should allow Shift+Insert to paste content from the clipboard, right?

`{ ShiftMask, XK_Insert, clippaste, {.i =  0} }`

Unfortunatelly it's not working. I have tried other keybindings that worked fine, but fingers have a memory of their own.

Thanks in advance!

**Comment by VineshReddy** [comment]
shift insert is working for me. something probably wrong on your side.

**Comment by cantao** [comment]
Well, decided to get back to xterm. I'll give it another try some time in the future. Thanks!
