### ISSUE TITLE
urlhandler does not work on underlined text

### ISSUE THREAD

**Issue by sourjyo0** [LukeSmithxyz/st#214]
\e[4mhttp://www.like.com\e[0m"
this does not work,add regex to remove \e[4m,\e[0m

**Comment by sourjyo0** [comment]
http://www.andre-simon.de/doku/ansifilter/en/ansifilter.php

**Comment by GasparVardanyan** [comment]
"\e[4mhttp://www.like.com\e[0m" works with my regex: https://github.com/GasparVardanyan/st/blob/master/config.h#L186
