### ISSUE TITLE
Resource use comparision between st and urxvt

### ISSUE THREAD

**Issue by zenny** [LukeSmithxyz/st#216]
@LukeSmithxyz I just checked the resource use between your build of st and urxvt (opening two instances of each) and found that st seems to use more resources than urxvt despite being minimal!? Screenshot at: https://paste.pics/95IAJ

Output:

```
[zenny@MACHINE-GA-970A-D3 ~]$ ps aux | grep urxvt
zenny    12140  0.0  0.0   2392   708 ?        S    09:24   0:00 /bin/sh -c urxvt
zenny    12141  0.1  0.0  41612 19788 ?        R    09:24   0:02 urxvt
zenny    13787  0.0  0.0   6336  2220 pts/2    S+   09:49   0:00 grep urxvt

[zenny@MACHINE-GA-970A-D3 ~]$ ps -aux | grep '/usr/local/bin/st'
zenny    13311  0.0  0.0  27740 14348 ?        S    09:42   0:00 /usr/local/bin/st
zenny    13329  0.0  0.0  27668 14188 ?        S    09:43   0:00 /usr/local/bin/st
zenny    13789  0.0  0.0   6340  2300 pts/2    S+   09:49   0:00 grep /usr/local/bin/st
```
Is this 'suckless' app sucks more resources than the 'bloated' ones? Just wondering! 

Cheers, and stay safe,
/z

**Comment by terriblephrases** [comment]
Where's the second urxvt, exactly? It's visible in neither your screenshot nor your ps report.

`/bin/sh -c urxvt` is precisely that, /bin/sh, not urxvt.

**Comment by Azumgi** [comment]
On your screenshot, `urxvt` instance takes ~19.5MB while `st` takes ~14MB (and we don't know much of it is shared). With all the bells and whistles Luke put on his fork this seems pretty reasonable to me.
