### ISSUE TITLE
Can't display Chinese character

### ISSUE THREAD

**Issue by sleeperzjf** [LukeSmithxyz/st#219]
Can't display Chinese character with either `ibus` or `fcitx`.

**Comment by dennisleexyz** [comment]
Try removing emoji font from `~/.config/fontconfig/fonts.conf` in the `monospace` category

**Comment by sleeperzjf** [comment]
I don't have any `monospace` category in my `~/.config/fontconfig/font.conf`.
![image](https://user-images.githubusercontent.com/65698607/84729493-6f111f80-afc6-11ea-943d-c262d6e4b9b6.png)
I haven't edited this file before, should I change something in it?

**Comment by LukeSmithxyz** [comment]
This is fontconfig question, not one related to this repository.

**Comment by sleeperzjf** [comment]
Sorry, it's just that all my other applications including `alacritty` and Luke's `dwm` and `dmenu`  builds can display Chinese characters. I just don't understand.

**Comment by LukeSmithxyz** [comment]
None of my builds ever specify a specific font. They simply look to the
system's default mono font, whatver you have it set as, with all its
fallbacks.

The solution would be either figure out what is amiss in the fontconfig
or recompile dwm/st while manually specifying the fonts.
On 20/06/16 06:05PM, sleeperzjf wrote:
> Sorry, it's just that all my other applications including `alacritty` and Luke's `dwm` and `dmenu`  builds can display Chinese characters. I just don't understand.
>
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/st/issues/219#issuecomment-645087371

--
https://lukesmith.xyz

**Comment by sleeperzjf** [comment]
I have specified the font in my `st` configuration file as I did with `dwm`:
![image](https://user-images.githubusercontent.com/65698607/84843726-4139e280-b07b-11ea-9cd6-de38bb3a97a2.png)
And I have the font installed.
To display Chinese characters, I have to specify the Chinese font in my `st` configuration file:
![image](https://user-images.githubusercontent.com/65698607/84843813-8231f700-b07b-11ea-9d62-84439211b160.png)
But it shouldn't be that way.
