### ISSUE TITLE
config.h

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/st#22]
this might be a stupid question, but some reason i can not locate the config.h file.

**Comment by focus85** [comment]
> @focus85 For my knowledge, you should edit config.h (It will be in the cloned folder) before building it. Edit than build it again.

the LARB install already build st, i just wanted to change the font size and transparency but i cant find the config.h file

**Comment by LukeSmithxyz** [comment]
It's in this repository. Make your edits and recompile.
