### ISSUE TITLE
urlhandler does not work with newlines

### ISSUE THREAD

**Issue by IvarWithoutBones** [LukeSmithxyz/st#220]
When using a smaller sized terminal, some urls get cut off and put on a new line. However, the alt+l urlhandler cant handle this, and just opens the url from the first line.

**Comment by LukeSmithxyz** [comment]
There should be a failsafe to prevent this. Are you seeing these urls in a specific program?

Multi-line urls should be working in typical terminal output and in mutt.

**Comment by IvarWithoutBones** [comment]
> Are you seeing these urls in a specific program?

Nope, this was regular output from git.
