### ISSUE TITLE
ControlMask|ShiftMask not working. 

### ISSUE THREAD

**Issue by paperbenni** [LukeSmithxyz/st#222]
```
	{ (ShiftMask|ControlMask),               XK_c,           clipcopy,       {.i =  0} },
	{ ShiftMask,            XK_Insert,      clippaste,      {.i =  0} },
	{ (ShiftMask|ControlMask),               XK_v,           clippaste,      {.i =  0} },
```
Pretty simple change, trying to make my build a little more "normal". 
Somehow does't work, the keybinding just doesn't get caught by st at all and gets passed on to the shell. 
The default st build uses exactly this binding, so it should work.
Default st works on my machine, with this binding.

**Comment by mamg22** [comment]
When you use shift in a key combination, the `XK_*` variables, the last letter in it needs to be in uppercase. In that case, the first line should be

    	{ (ShiftMask|ControlMask),               XK_C,           clipcopy,       {.i =  0} },

**Comment by paperbenni** [comment]
Thank you. 
I feel dumb now xD
