### ISSUE TITLE
Swallow patch (dwm) ceases to work. Still works on a standard st build.

### ISSUE THREAD

**Issue by a11998** [LukeSmithxyz/st#227]
First issue ever created on github -- hope I am going about this correctly.

I've installed the swallow patch on dwm per one of Luke's videos. It has worked consistently well.

After installing Luke's build of st, swallowing has stopped working. It simply opens a new window as if the swallow patch wasn't installed.

Upon recompiling my st build with only the scrollback patch installed, swallowing works again. Recompile Luke's st build, and swallowing stops working.

For some odd reason, I seem to recall swallowing working before I rebooted earlier today, even while still running Luke's st build. I have not modified Luke's st build in any way.

5.7.5-arch1-1

**Comment by mackarelfish** [comment]
Make sure to add this entry on your dwm config.h rules array
```
{ "St",      NULL,     NULL,           0,         0,          1,           0,        -1 },
```
