### ISSUE TITLE
visualbell patch not applying on ur build

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/st#228]
<img width="1087" alt="Screen Shot 2020-06-28 at 20 31 47" src="https://user-images.githubusercontent.com/11430921/85961607-fb85ef80-b981-11ea-9317-18bcb3a41b3e.png">
<img width="1280" alt="Screen Shot 2020-06-28 at 20 31 34" src="https://user-images.githubusercontent.com/11430921/85961612-ffb20d00-b981-11ea-9183-21e3384731c5.png">
<img width="855" alt="Screen Shot 2020-06-28 at 20 58 20" src="https://user-images.githubusercontent.com/11430921/85961625-21ab8f80-b982-11ea-9375-2867fd1e4706.png">

**Comment by terriblephrases** [comment]
Don't be a consoomer. If you care, just apply it manually, make a patch for luke's build, and share it, and maybe you'll have learned something. Both versions would be simple edits, though especially `st-visualbell-0.8.3.diff`.

**Comment by adrian-gluu** [comment]
I tried but it failed, that's why am asking luke's help

**Comment by adrian-gluu** [comment]
@LukeSmithxyz i i send you a PR you will apply it? in ur master branch "visual bell" patch?
