### ISSUE TITLE
A better default colorscheme? What's your favorite? 🤔

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/st#23]
I'm getting a little annoyed by the default solarized colors and am thinking of replacing them.

Does anyone have any particular colorscheme that they would recommend?

Obviously it should be somewhat generic since it's default (i.e. not all hot colors), but I'm pretty open. I just want it to have variant enough colors and look okay in most circumstances.

**Comment by kgnugur** [comment]
I would recommend **gruvbox. ** It has less emphasis on blue than solarized. You've probably heard it already , it's pretty good.

**Comment by LukeSmithxyz** [comment]
@kgnugur I actually really like this one. Haven't tried it until now, but it looks good.

@bigboymate Understandable, but I want to be sure that even noobs have a pretty usable setup off the bat since this is what the LARBS scripts install. I'm sort of thinking of removing pywal, which means that this theme would be more important. Of course I might just have it all in `~/.Xdefaults` instead and revert `st` back to its orignal colors.

**Comment by BankOfIndia** [comment]
`export TERM=vt100` is the true patrician choice. Every other colorscheme is bloated and you will jump from it.

**Comment by JShorthouse** [comment]
I can second **Gruvbox**, been using it for a couple of years now and have no desire to switch to anything else.
I see that you've already taken a look, but for the convenience of others reading this thread, here's a link to the github page with previews:
https://github.com/morhetz/gruvbox

It's worth noting that for some reason I don't fully understand the colours don't display properly in some terminals by default, you have to do some extra steps listed here:
https://github.com/morhetz/gruvbox/wiki/Terminal-specific
(I had to source the `gruvbox_256palette.sh` script in my .zshrc and then all the colours displayed perfectly)

**Comment by LukeSmithxyz** [comment]
Yeah, honestly the more I use gruvbox the more I like it, it's working great. I'm going to set it as the default now, but if anyone has any other suggestions, feel free to offer them.

**Comment by adimanea** [comment]
Another vote for **Gruvbox** from me as well. I generally read in a sepia theme, including in Zathura and I find that Gruvbox complements it very well. My only complaint (which will probably wear on you as the blue in solarized) is the red. If you're using it in vim, there may be too many keywords highlighted in red, which can be annoying. My brain says reds belong (mostly) to errors or things of top importance, not some function name or harmless keyword.

But you can desaturate, customize or mix them yourself, based on the [original](https://github.com/morhetz/gruvbox) scheme (mentioned by @JShorthouse as well). I also use it in st and love it.

**Comment by foldfree** [comment]
gruvbox is the best, it's based on solarized minus the blue.
It's also well implemented in text editors like vim or kakoune, that has it built-in already, (pywal easily broke syntax highlighting for me)
there even is a gruvbox gtk-theme, so you can have a consistent environment switching from cli to gui programs.

**Comment by geowy** [comment]
I like brogrammer, gruvbox is too dull IMO

https://vimcolors.com/398/brogrammer/dark

**Comment by StillANixRookie** [comment]
i second dracula.

my favourites

```
!city-lights
#define cblkd #181e24
#define credd #d95468
#define cgrnd #8bd49c
#define cylwd #ebbf83
#define cblud #539afc
#define cgntd #b62d65
#define ccynd #70e1e8
#define cwhtd #718ca1
#define cblkl #333f4a
#define credl #d95468
#define cgrnl #8bd49c
#define cylwl #f7dab3
#define cblul #5ec4ff
#define cgntl #b62d65
#define ccynl #70e1e8
#define cwhtl #b7c5d3
```

```
!deepjyot
#define cblkd #1E2541
#define credl #F0719B
#define cgrnl #5AF7B0
#define cylwl #FFA56B
#define cblul #57C7FF
#define cgntl #C792EA
#define ccynl #89DDFF
#define cwhtl #EEFFFF
#define cblkl #354274
#define credd #F02E6E
#define cgrnd #2CE592
#define cylwd #FF8537
#define cblud #1DA0E2
#define cgntd #A742EA
#define ccynd #47BAE8
#define cwhtd #DEE6E7
```

**Comment by bepolymathe** [comment]
Pencil ?

**Comment by LukeSmithxyz** [comment]
Okay I'm going to go ahead and close this issue since I've changed the default to Gruvbox.

Of course I've put documentation up as to how to change the colors via Xresources so hopefully everyone's needs can be met now. Thanks everyone!
