### ISSUE TITLE
update to st version 0.8.4?

### ISSUE THREAD

**Issue by linuxclowns** [LukeSmithxyz/st#230]
0.8.4 includes a patch to fix image flickering in w3m. Any chance of an update?

**Comment by KerrLiu** [comment]
> 0.8.4包含一个补丁，用于修复w3m中的图像闪烁。有更新的机会吗？

I updated it,But I use alpha patches,w3m not show image for webpage.

**Comment by stormmurdoc** [comment]
bump

**Comment by LukeSmithxyz** [comment]
Well the w3m thing is hardly a "fix."

I have no urgent interest in updating. Most of the bugfixes I had committed on my own.

I will probably eventually, but it's either repatch everything for 0.8.4 or deal with a bunch of conflicts manually. If anyone's already done this for a fork of this build, you are welcome to PR.

**Comment by hurricanehrndz** [comment]
I have rebased a lot of the patches included in this repo onto [0.8.4.](hurricanehrndz/st). I have not included the scrollback or externalpipe patches, as I have no need for them. Perhaps, someone may find my fork as a good starting point.

**Comment by LukeSmithxyz** [comment]
I might look into it. I consider externalpipe an absolute must and scrollback is effectively a must until that new scroll program works without bugs.

**Comment by BachoSeven** [comment]
@LukeSmithxyz regarding the scroll program, version [0.1](https://tools.suckless.org/scroll/) was released, thought it might be relevant to this.

**Comment by LukeSmithxyz** [comment]
Thanks for the update. scroll seems to be working much more cleanly now on tiling wms. I might start implementing it and st 0.8.4 soon.

**Comment by LukeSmithxyz** [comment]
This will be up tomorrow or so.
