### ISSUE TITLE
st crushed while using nvim

### ISSUE THREAD

**Issue by Saurav-Paul** [LukeSmithxyz/st#232]
Whenever i try to use nvim sneek, it crushes. I tried with other terminal they works fine.. Can you fix it? 

I am running manjaro.

I have Libxft-bgra on my system.

**Comment by grravity** [comment]
st is crashing when pasting certain texts into neovim for me, not sure what's causing it. Some texts cause it to crash and some don't, seems like a character issue, maybe emoji?
Artix.

**Comment by myself379** [comment]
Hi @Saurav-Paul, try replacing libxft-bgra to libxft-bgra-git, so far I solved my issue
