### ISSUE TITLE
Is there anyway to yank a line without selecting them with mouse or touch pad

### ISSUE THREAD

**Issue by shahid777-py** [LukeSmithxyz/st#234]
It's a waste of time using mouse to copy a line .than with a keyboard shortcuts any help would be so awesome.

**Comment by vladdoster** [comment]
Depends... You can use `alt + o` to copy commands output. Or there is another shortcut to copy urls.

**Comment by donihalim** [comment]
You can use `tmux`, but em..

**Comment by shahid777-py** [comment]
> You can use `tmux`, but em..

Oops.

**Comment by shahid777-py** [comment]
Why can't we copy that using vim like yanking in shell and in st

**Comment by LordRusk** [comment]
there is a patch `vimbrowser` which basically just gives you a terminal wide vim buffer, you could add it to your fork of lukes terminal, It's in mine build of st which has all of lukes `alt+(l|o|y)`,

**Comment by shahid777-py** [comment]
> jthere is a patch `vimbrowser` which basically just gives you a terminal wide vim buffer, you could add it to your fork of lukes terminal, It's in mine build of st which has all of lukes `alt+(l|o|y)`, there is this build to try it out on, from the original creator. [here](https://github.com/juliusHuelsmann/st)

Thanks... I'll give a replay

**Comment by shahid777-py** [comment]
> jthere is a patch `vimbrowser` which basically just gives you a terminal wide vim buffer, you could add it to your fork of lukes terminal, It's in mine build of st which has all of lukes `alt+(l|o|y)`, there is this build to try it out on, from the original creator. [here](https://github.com/juliusHuelsmann/st)

Also why vim is not showing cursor I mean it's invisible in normal mode ..and neovim works pretty well why is that

**Comment by vladdoster** [comment]
> > jthere is a patch `vimbrowser` which basically just gives you a terminal wide vim buffer, you could add it to your fork of lukes terminal, It's in mine build of st which has all of lukes `alt+(l|o|y)`, there is this build to try it out on, from the original creator. [here](https://github.com/juliusHuelsmann/st)
> 
> Also why vim is not showing cursor I mean it's invisible in normal mode ..and neovim works pretty well why is that

Can you close this issue?  It seems a bit out of scope and isn't an actual issue related to st.

**Comment by shahid777-py** [comment]
> > > jthere is a patch `vimbrowser` which basically just gives you a terminal wide vim buffer, you could add it to your fork of lukes terminal, It's in mine build of st which has all of lukes `alt+(l|o|y)`, there is this build to try it out on, from the original creator. [here](https://github.com/juliusHuelsmann/st)
> > 
> > 
> > Also why vim is not showing cursor I mean it's invisible in normal mode ..and neovim works pretty well why is that
> 
> Can you close this issue? It seems a bit out of scope and isn't an actual issue related to st.

Yesss
