### ISSUE TITLE
change shortcut

### ISSUE THREAD

**Issue by furanzoni** [LukeSmithxyz/st#236]
how can I change alt+c and alt+v to ctrl+shift+c and ctrl+shift+v? thanks

**Comment by mgdawber** [comment]
You should be able to edit config.h
about line 240 or so, look at these two lines
`
 { MODKEY,               XK_c,           clipcopy,       {.i =  0} },
 { MODKEY,               XK_v,           clippaste,      {.i =  0} },
`
You want to change them to
`
 { MODKEY|ControlMask,               XK_c,           clipcopy,       {.i =  0} },
 { MODKEY|ControlMask,               XK_v,           clippaste,      {.i =  0} },
`
And then sudo make install

Hopefully that works for you!

**Comment by furanzoni** [comment]
> You should be able to edit config.h
> about line 240 or so, look at these two lines
> 
> ```
>  { MODKEY,               XK_c,           clipcopy,       {.i =  0} },
>  { MODKEY,               XK_v,           clippaste,      {.i =  0} },
> ```
> 
> You want to change them to
> 
> ```
>  { MODKEY|ControlMask,               XK_c,           clipcopy,       {.i =  0} },
>  { MODKEY|ControlMask,               XK_v,           clippaste,      {.i =  0} },
> ```
> 
> And then sudo make install
> 
> Hopefully that works for you!

Thanks for the answer! But it didn't work, here is how my `config.h` looks like:
![image](https://user-images.githubusercontent.com/48025993/87840034-de1bb580-c89d-11ea-8ac7-cff5e2c11526.png)
