### ISSUE TITLE
Drawing lines are not visible.

### ISSUE THREAD

**Issue by ZaxonXP** [LukeSmithxyz/st#246]
I was using the perl code to draw lines in the terminal. On the `st` terminal the lines are not visible, where ont `xterm` are ok.

I have the same color configuration for both `xterm` and `st`.
 
![2020-09-21_13-58](https://user-images.githubusercontent.com/6058640/93763960-96553980-fc12-11ea-8075-dc4e51ceffac.png)

`xterm` on the left `st` on the right.

Here is the test code: 
```
#!/usr/bin/perl

use 5.010;
use Text::ANSITable;
 
# don't forget this if you want to output utf8 characters
binmode(STDOUT, ":utf8");
 
my $t = Text::ANSITable->new;
 
# fill data
$t->columns(["name"       , "color" , "price"]);
$t->add_row(["chiki"      , "yellow",    2000]);
$t->add_row(["lays"       , "green" ,    7000]);
$t->add_row(["tao kae noi", "blue"  ,   18500]);
 
# draw it!
print $t->draw;
```

**Comment by ZaxonXP** [comment]
I changed the transparency and it looks that the borders are drawn with black color. Which Xresource is used to draw the borders?

**Comment by LukeSmithxyz** [comment]
The color chosen for that border isn't chosen by st, but whatever perl function uses them. You can probably toy around with your background and color0 xresources color and that might alleviate your issue.
