### ISSUE TITLE
Your build of st as a patch.

### ISSUE THREAD

**Issue by ZaxonXP** [LukeSmithxyz/st#247]
I was trying to apply other patches from suckless.org but it failed. So I wonder that the changes you did are so extensive that they does not allow the other patches to be applied.

Would it be possible to create your build as a patch that it would allow to add other patches?

Regards,
Piotr

**Comment by paniash** [comment]
@ZaxonXP Maybe you could copy `config.h` to `config.def.h` and manually patch the required patches from suckless.org. It does work but it is time consuming.
