### ISSUE TITLE
Adding the Ctrl-Y key-binding for pasting mouse-selection/selpaste

### ISSUE THREAD

**Issue by reverseila** [LukeSmithxyz/st#249]
https://github.com/LukeSmithxyz/st/blob/8ab3d03681479263a11b05f7f1b53157f61e8c3b/config.h#L257

Before I use the Luke's build I was using the Debian's stterm  (0.8.4). There was a key-binding for pasting **mouse selection**, that I guess it is referred to as *selpaste* in the source code. It was very handy because `Shift-Insert` is kinda confusing to me (it sometimes acts as `Ctrl-V` and sometimes pastes mouse selection) and I could use it when I had no mouse around to do the mid-click. There is a line of code in vanilla st:
`{ TERMMOD,              XK_Y,           selpaste,       {.i =  0} },`
when I add this to Luke's build, and then
`make && sudo make install`
it compiles with no errors, but nothing happens (key-binding doesn't work).
Is there already any such key-binding in the Luke's build? If not How can I add this key-binding?

**Comment by WudUpA** [comment]
ST is broken... luke doesnt support it anymore either.
