### ISSUE TITLE
ST wont start using old larbs

### ISSUE THREAD

**Issue by WudUpA** [LukeSmithxyz/st#252]
When I try to open a terminal using mod+enter, it didnt open a terminal.  So, I used dmenu to open another terminal that i had installed and tried to open st and this is the error that i got:

malloc(): corrupted top size
[1]    29892 abort (core dumped)  st

I think some update broke it... but i have no clue which one. If i knew which update broke it, i could downgrade and it should work.

**Comment by WudUpA** [comment]
I cloned the latest st from suckless and it worked.  But the lukesmith verson doesnt work.  There is something wrong with the config.h file because when i sudo make clean install, it still gives me the error.  So much for installing this ST.

**Comment by skrrtskrrtman** [comment]
I am experiencing this issue after installing via larbs

**Comment by WudUpA** [comment]
I think to fix it, i upgraded python.
