### ISSUE TITLE
Colors at launch patch. Can you please integrate it in your version?

### ISSUE THREAD

**Issue by ZaxonXP** [LukeSmithxyz/st#257]
Dear Luke,

I tried to integrate this patch in the master branch of your st code, but somehow it does not work.
I created a patch file [st-colors-at-launch-0.8.2.diff.zip](https://github.com/LukeSmithxyz/st/files/5558962/st-colors-at-launch-0.8.2.diff.zip) but it does not work when I apply to your code.

I tried to patch original ST shources with that [patch](https://st.suckless.org/patches/colors_at_launch/) and then it is working correctly (it changing the colors of the terminal when using with the `-C` option like `st -C "#AAAADD@0" -C "#FFFFFF@20"`)

Kind regards,
Piotr

**Comment by LukeSmithxyz** [comment]
My first inclination would be to think that it is interfering the the xresources patch since colors are read from those setting in my build, if you have them.

**Comment by terriblephrases** [comment]
Yes, the "colors at launch" patch sets the `colorname[]` variable some lines before the xresources patch overwrites it with line `config_init();`.
The easiest way to make "colors at launch" work on Luke's build seems to be just deleting `config_init();` to disable the xresources patch. 
If you just have to make both work, change the order in which the contents of `case 'C':` and line `config_init();` appear somehow, like break the `case 'C':` bit into an if-statement after `config_init();`.
