### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by FillePiano** [LukeSmithxyz/st#258]
Hi!
The zoom function in st does not work for me, when I press Alt+Shift+Up it scrolls. I've tried to rebuild st but with no success. Someone alsa suggested that I may have a another binding that interferes with this binding, but I have larbs... Please help...

**Comment by antenore** [comment]
It could be that is your window manager that grabs this key shortcuts.

Try to either change the shortcut in st, with something that is not used by your WM, or the other way around, check Yokut WM settings.

**Comment by antenore** [comment]
BTW, with up, you mean Alt+Shift+PgUp , right? ;-)

**Comment by FillePiano** [comment]
Yes PgUp, I use dwm... just installed larbs

**Comment by LukeSmithxyz** [comment]
Which alt are you holding down (left or right)? Are you using a special keyboard layout?

**Comment by FillePiano** [comment]
Left one, yes I use a swedish keyboard, but it has worked before... But I changed the shortcuts and now it works even though the shortcut is a bit more uncomfortable.
