### ISSUE TITLE
Underscores too thin and dissapearing/reappearing with default settings.

### ISSUE THREAD

**Issue by sarpu** [LukeSmithxyz/st#259]
I have a small issue with underscores. With the default font size, underscores disappear/reappear based on the position of the cursor. I have noticed that this is the case for default color. For example, regular filenames in a directory with underscores also have this issue, but directories do not. Below is a screen capture showing the issue. I tried to replicate the issue with just suckless, and I don't experience the issue there, so I think it has something to do with the default settings here, but I couldn't figure it out. I would be grateful for any suggestions/hints and thank you for the project and  all the videos!

![output](https://user-images.githubusercontent.com/13471031/100524688-29b56880-3188-11eb-8e27-a3043f26e389.gif)

**Comment by LukeSmithxyz** [comment]
So what is your system default monospace font and size? I haven't had any kind of issue like this, but it's possible that there is some strange font being called for the underscores that produces this problem.

**Comment by sarpu** [comment]
Ubuntu Mono 13 :sweat_smile:
