### ISSUE TITLE
mouse scroll down isn't work

### ISSUE THREAD

**Issue by henryzxb** [LukeSmithxyz/st#26]
i can't use mouse to scroll down,while scroll up is working properly,does anyone has the same problem?

**Comment by LukeSmithxyz** [comment]
To be clear, the scroll down ability only works if you are within history. You cannot simply open an instance and scroll down so that the prompt is in the middle of the screen. Is this what you're talking about?

**Comment by henryzxb** [comment]
sorry for my bad english,what i mean is that when I edit a file with a text editor in st terminal, I can't use the mouse wheel to browse the file content.

**Comment by LukeSmithxyz** [comment]
Then this is intended functionality. Scrolling back in a terminal emulator shows previous output and commands while scrolling back in, say, vim is something altogether different: moving your cursor up lines and then initiating a screen rewrite.

Look up how how to scroll with your mouse in whatever program you are running.

**Comment by hedich** [comment]
i am a bit confused, scrolling up works as expected but down does not

in VIM, using same file in urxvt scrolling up and down works as expected
but in st only up works, trying to scroll down it "glitches" on the same line (its trying to go down but it does not work it just stays in place)

i really doubt this is indented behavior.

**Comment by tokumei27** [comment]
So it was just a spacevim problem. And not to sound obnoxious, but you aren’t meant to use the mouse in vim in the first place. If you want that feature, you might like gVim.

**Comment by hedich** [comment]
Your preferences aren't a set rule, just because you don't use the mouse does not mean other people cant. its perfectly fine to use the mouse in vim if you feel like it, i like to use the mouse for just that scrolling.

(you do sound very obnoxious btw and a very unnecessary reply to an already solved problem.)

**Comment by Midren** [comment]
After merging #229, it is now possible to easily integrate scrolling with vim. You can just add
```vim
set ttyterm=sgr
```

**Comment by chadostlund** [comment]
@Midren Thanks for pointing that out here. Now I can scroll up and down in vim using mousewheel.
