### ISSUE TITLE
[Solved] Invisible chinese characters

### ISSUE THREAD

**Issue by zihenlin** [LukeSmithxyz/st#265]
I am able to input chinese character, however, it is not showing on the terminal. I could copy the invisible chinese characters and paste to other applications, the characters show. I tried inverting the bg/fg colour, but to no avail. 

Could it be that the chinese characters are rendered with bg colour? 

The chinese characters could be displayed and input properly on browser and alacritty.

**Comment by zihenlin** [comment]
A vanilla st package from arch repo could render chinese character as well. I tried disabling boxdraw-related in config.h and rebuild, it didn't help. 

Thank you for you attention!

**Comment by ypcodes** [comment]
字体的问题，把其中一个字体改成中文。。。
![image](https://user-images.githubusercontent.com/71961228/104087379-373b3380-529a-11eb-9a00-ca7102cb15b3.png)

**Comment by zihenlin** [comment]
已经放了，还是不行。。。

**Comment by ypcodes** [comment]
你确定你的系统有对应的中文字体吗，字体名字对了吗？
![image](https://user-images.githubusercontent.com/71961228/104115511-1f6fb800-534b-11eb-8c4c-b4004d3f683d.png)
左边就是我把字体名字搞错了没有显示中文，右边用的是文泉驿等宽微米黑

**Comment by zihenlin** [comment]
我用的是source hans, 由于字体名字都是英文字母，在fetch 上能显示出来。也用fc-list 检查正确名字了。

**Comment by ypcodes** [comment]
应该是没问题的，把他的克隆下来，我就改了字体就可以了
![image](https://user-images.githubusercontent.com/71961228/104116602-ea686300-5354-11eb-9f04-d8015fe5adac.png)
![image](https://user-images.githubusercontent.com/71961228/104116630-416e3800-5355-11eb-89a8-0104f185c46f.png)

**Comment by zihenlin** [comment]
好的， 谢谢你！
