### ISSUE TITLE
Zoom feature as a patch?

### ISSUE THREAD

**Issue by BeanieBen9990** [LukeSmithxyz/st#267]
Is there a way Luke or someone more talented and well versed in C than I could port the zooming/text sizing feature to a patch, so that I and others could patch that functionality into our own builds more easily? It would be super helpful as I haven't been able to find any other build of st that has this functionality, even though it's insanely convenient. Thanks!

**Comment by terriblephrases** [comment]
Text resize/zoom has been in Suckless' st since 2017 at least, bound to Ctrl+Shift+PgUp/PgDn/Home. Search for "zoom" in config.h to rebind it.

**Comment by LukeSmithxyz** [comment]
Yeah. This is in the default build.

**Comment by BeanieBen9990** [comment]
Wow that's something I totally should have known lol.. thanks!
