### ISSUE TITLE
ST crashes while scrolling more than ~740 lines in Neovim.

### ISSUE THREAD

**Issue by jameskeim** [LukeSmithxyz/st#272]
Not sure how to pinpoint this issue. I've been opening some some large configuration files in Neovim while using Luke's ST. Whether I scroll through the file using a mouse, keyboard directional keys, or even jump to line 720 and start scrolling from there, the terminal crashes while scrolling somewhere between 750 and 850 lines. I can edit the same file in LXTerminal or Alacritty without issue.

I'm running the program on an 8gb Pi4 running 32bit Raspbian, i3-gaps, and Neovim (obviously). Memory usage seems quite low. Happy to provide any other information that might be useful.

**Comment by LukeSmithxyz** [comment]
Do you have libxft-bgra installed?
