### ISSUE TITLE
Zoom and scroll

### ISSUE THREAD

**Issue by CoderBasis** [LukeSmithxyz/st#273]
Hi,
It seem like there is a conflict somewhere in the config. If I leave your st config as it is I can only scroll, but if I interchange MODKEY and TERMMOD in the scroll and zoom commands resp. I can only zoom. It is a big issue and I've always had this issue since I installed larbs. I've tried different method like changing bindings and change Mod1key for ControlShift, but nothing seems to work.

Please help.

**Comment by LukeSmithxyz** [comment]
Are you using Alt or Alt-grab? Right alt is alt-grab in my dotfiles.

**Comment by CoderBasis** [comment]
I have a swedish keyboard layout and my x220 only have one alt, the other one says Alt Gr on the actual button.

**Comment by LukeSmithxyz** [comment]
I suspect the `remaps` script is interfering with your keyboard layout. Open up `~/.local/share/bin/remaps` and comment out the `setxkbmap` and `xcape` lines or at least remove the `-variant altgr-intl` portion and log out and back in.

**Comment by CoderBasis** [comment]
I suspect you meant .local/bin/remaps

there is no line that says -variant altgr-intl

**Comment by CoderBasis** [comment]
Solved it, the problem was in my /etc/X11/xorg.conf.d/00-keyboard.conf file. I had set alt to toggle or something
