### ISSUE TITLE
st don't cover all screen

### ISSUE THREAD

**Issue by kmj9** [LukeSmithxyz/st#275]
It build fine but the window of st don't cover all screen (I set my dwm to not having gaps).
On st's config.h I change fontsize to 24 and opacity to 0.95.
The gaps are located bottom of screen and to the right. (I include a picture
![pic-full-210206-1818-57](https://user-images.githubusercontent.com/78656735/107125069-e7a35400-68a7-11eb-8ade-b49ed00ff0a1.png)
)
Not sure what should I change in config because before update 0.8.4 st was working fine.
Any ideas ?

**Comment by LukeSmithxyz** [comment]
Oh I think that my original build had the `anygeometry` patch, but the new one doesn't yet. I'll look into it. I think that's the patch.

**Comment by monosans** [comment]
Have you tried setting `static const int resizehints` in dwm's config.h to `0`?

**Comment by kmj9** [comment]
ok I change that setting to 0 rebilded and it works :) Problem solved. Thank you

**Comment by LukeSmithxyz** [comment]
I might just change this setting by default because I think most people would prefer it.

**Comment by xerus2000** [comment]
Running latest arch version of `st-luke-git`, still encountering this.

These are some instances with different font sizes under KDE Plasma with Krohnkite for tiling:
![image](https://user-images.githubusercontent.com/13354331/109395751-549d8d00-792e-11eb-8ebf-e1878dffd071.png)

**Comment by LukeSmithxyz** [comment]
Well I can't help what KDE Plasma decides to do with windows. There might be a setting that enforces perfect tiling, but that is equivalent of how it's done in dwm.
