### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by jeanpierredevilliers** [LukeSmithxyz/st#276]
The fonts seem to be rendering a lot differently from before.  Has anyone else experienced this or know whether this is perhaps intentional?  It seems a lot harder to read text on the terminal now.

Apologies for the vague description as I'm not sure how exactly to word it to make it clear and unambiguous.  It's almost as if the necessary fonts are not installed but I made sure to (again) check I have all the fonts that are described in `~/.config/fontconfig/fonts.conf`.

**Comment by LukeSmithxyz** [comment]
You'll have to describe your problem. The default font size changed. That's the only thing I can think of.
