### ISSUE TITLE
PKGBUILD errors out

### ISSUE THREAD

**Issue by TheSre** [LukeSmithxyz/st#278]
Hi, the `PKGBUILD` currently fails with this error:
```
install: cannot stat '.Xdefaults': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

I believe it's from the line below...was the `.Xdefaults` file removed from the repo?
https://github.com/LukeSmithxyz/st/blob/03fe8634cd3f2f3cbd1679be84b465d63caafa3c/PKGBUILD#L44

Also, thanks for your work on this!

**Comment by LukeSmithxyz** [comment]
Should be fixed now.
