### ISSUE TITLE
Alt + c for copying doesn't seem to work

### ISSUE THREAD

**Issue by lyh970817** [LukeSmithxyz/st#283]
Alt + y works for pasting but alt + c doesn't work. After visually selecting some texts after the command prompt and pressing alt + c I can't find anything in the clipboard.

**Comment by YacineSahli** [comment]
It works for me, something must be wrong on your side.

**Comment by cortex3** [comment]
same here, not sure what's going wrong since the config is looking good.

**Comment by cortex3** [comment]
Hi @lyh970817,
In my setup with bspwm I have alt + c bound to do something on top of the copy within st. 
This used to work with me in prior versions but doesn't work with the latest commits.
Removing my bspwm shortcut for alt + c resolved this issue for me.

Not sure if this is any help to you.

**Comment by freezboltz** [comment]
Hey! @lyh970817 check if your other keybindings are overwriting it or not.
