### ISSUE TITLE
Resizing terminal breaks output adjustment

### ISSUE THREAD

**Issue by sudoLife** [LukeSmithxyz/st#285]
Steps to reproduce:

1. Run neofetch (or anything, really)
2. Make terminal smaller
3. Make it bigger again
4. Everything looks messed up now

I thought it was my customization's fault, but stock config does not help.

**Comment by narukeh** [comment]
same
https://github.com/LukeSmithxyz/st/issues/284#issuecomment-812914514

**Comment by BachoSeven** [comment]
This can be closed as it's solved by https://github.com/LukeSmithxyz/st/commit/60add40bd1bcb1548fe264c8e809910049b2676e
