### ISSUE TITLE
Unicode characters with two letters get cut off

### ISSUE THREAD

**Issue by Fooftilly** [LukeSmithxyz/st#286]
When you write letters such as Ǆ, ǅ, ǆ they get cut off. This affects all characters which are longer than one letter such as ﬃ. This is also an issue when writing in neovim because characters get drawn at top of each other.  It is possible to separate letters into multiple characters, but that doesn't solve the issue, because there are cases where you need the exact Unicode character.

**Comment by Abhishek-Deshmukh** [comment]
same issue
![st-half-emojis](https://user-images.githubusercontent.com/42207326/116537017-4c000d80-a903-11eb-8c44-5ddfa0d1491e.png)

**Comment by LukeSmithxyz** [comment]
This is libxft issue, I believe, or at least an issue at a lower level than my build or any other build of st. It's up to them to patch it.
