### ISSUE TITLE
Backspace key not working

### ISSUE THREAD

**Issue by parmort** [LukeSmithxyz/st#29]
The backspace key is exhibiting some weird behavior. After typing in something and hitting backspace, whitespace is inserted. In essence, backspace acts like the spacebar visually, but internally it recognizes the backspace.

If `|` is the cursor:

```
$ exit|
```
After hitting backspace once
```
$ exit |
```
Spamming backspace:
```
$ exit    |
```
And then hitting enter:
```
$ exit
$ |
```

I don't know if that helps or not.

**Comment by parmort** [comment]
Thanks This helped a lot!

**Comment by vhoyer** [comment]
hmm, I'm on ubuntu and I, couln't find a ~/.Xresources file in my $HOME directory. I have one in a `~/dotfiles` folder of mine, and running `rxdb ~/dotfiles/.Xresources` with the `*cursorColor`, I commented it, reloaded it and it didn't have any effect, the problem still persists, anyone has an idea of how to fix it? perhaps there is another xresources file being run, or something I don't know?
