### ISSUE TITLE
Not sure about the error

### ISSUE THREAD

**Issue by afrid83** [LukeSmithxyz/st#297]
<img width="1440" alt="Screenshot 2021-05-09 at 10 06 05 AM" src="https://user-images.githubusercontent.com/59523682/117560750-2cf53e80-b0ae-11eb-89a3-c57fdb0244aa.png">

Unable to build the software.... : (

**Comment by decantr** [comment]
Are you running on Ubuntu? If so you are likely missing `libx11-dev`

**Comment by afrid83** [comment]
Nope, I use mac with M1

**Comment by decantr** [comment]
You are trying to build st on macos?

**Comment by narukeh** [comment]
You are missing dependencies. Look at this to know which dependencies you need:
https://aur.archlinux.org/packages/st-luke-git/
Once you install those, you will have no problem building.
( It is recommended to have the file ~/.config/fontconfig/fonts.conf )

**Comment by afrid83** [comment]
@decantr Yep I am trying to build st on macOS

**Comment by afrid83** [comment]
@narukeh Thanks!

**Comment by afrid83** [comment]
Solved after installing all the dependencies
Thanks Guys!

**Comment by bowen-song** [comment]
- @afrid18 Hi, could you please go into more detail about how you were able to compile this on Mac? After installing the dependencies (not sure if I got them all), I am getting the error 
`x.c:11:10: fatal error: 'X11/Xatom.h' file not found`

I've removed the -lrt var from `config.mk`, and done `brew install libxft nurses libxext git` but am getting the above error.

Thank you!

**Comment by afrid18** [comment]
Hey @bowen-song. That was the same issue I encountered, you are missing a package called ```libx11-dev```.
Also make sure to get info about that package:
```brew info libx11-dev```
Try to install it through:
```brew install libx11-dev```
You probably encounter another issue for [harfbuzz](https://github.com/harfbuzz/harfbuzz) package. Also make sure to build harfbuzz package. Here is the [Documentation](https://harfbuzz.github.io/).
Hope it helped.

**Comment by bowen-song** [comment]
Hi @afrid18, thanks for the response. For my brew, there is no package called `libx11-dev`. `Brew info libx11-dev` returns `Error: No available formula with the name "libx11-dev". Did you mean libx11?`

I have already installed libx11 and harfbuzz (through brew, not separate build).

When I make install after reinstalling libx11, I still see the same error. Interestingly, if I install `xquartz`, I am able to build, but I cannot run st at all (output is `Can't open display`).

Hope you can help troubleshoot.

**Comment by afrid18** [comment]
Yes sure, @bowen-song I will surly help you. But I have my mac given for repair. So I will try again when I get my mac back,  to install on my machine and then I will tell you what process I have gone through.

Also I use macbook with M1

What is yours??

**Comment by bowen-song** [comment]
@afrid18 No worries, I would really appreciate your help once you get the MacBook back. Thank you very much!

I have the M1 MacBook Air.

**Comment by afrid18** [comment]
Hello @bowen-song, I didn't receive my MacBook yet. But I came across this package called libxft.
```
brew install libxft
```
Could you please try after installing this package.

**Comment by bowen-song** [comment]
Hi @afrid18, I had already installed libxft. Reinstalled package with `brew reinstall libxft` but still the same error. Thanks for always keeping my issue in mind, I appreciate your help!

**Comment by narukeh** [comment]
libxft NO
libxft-bgra YES
you need this for lukes suckless stuff: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libxft-bgra

**Comment by psotou** [comment]
hey @bowen-song, I'm currently facing the same issue as yourself. Did you find any workaround? Brew only finds `libxft` and not `libxft-dev` :/

**Comment by bowen-song** [comment]
@psotou No, sorry I wasn't able to figure this out either unfortunately. Searched pretty widely for a solution, but gave up in the end. Would appreciate a ping if you end up figuring this out though!
