### ISSUE TITLE
Can't open st in ubuntu

### ISSUE THREAD

**Issue by rafasaurus** [LukeSmithxyz/st#30]
OS: Ubuntu 16.04
After compiling, changing the font to font that I have, and installing st as mentioned, I can't run it, no error message is being printed.

* The cpu usage is 100%, it seems that it tries to read some data, but can't.
* After some tweaks with original st i found out that if I add extra "colorname" in `config.h` it does exact same thing ad above.

So I'm just wondering if you put some config that relates only for your setup ?

**Comment by terriblephrases** [comment]
Why such an old Ubuntu? I use Luke's build in Ubuntu 18.04 on Windows Subsystem for Linux, no problems.

**Comment by rafasaurus** [comment]
I compiled it in 18.04 vm, and it works, idk what is the problem.
How do you run xserver in WSL?

**Comment by rafasaurus** [comment]
just tried 16.04 vm newly build, and it works.

**Comment by terriblephrases** [comment]
> How do you run xserver in WSL?

There are Windows-native X servers, like [VcXsrv](https://sourceforge.net/projects/vcxsrv/), that the WSL programs can easily connect to.
