### ISSUE TITLE
nerdfonts glyphs chipped into half 

### ISSUE THREAD

**Issue by siduck76** [LukeSmithxyz/st#302]
Hi luke , I use [logo-ls](https://github.com/Yash-Handa/logo-ls)  as ls which shows file type and folder icons but the icons look half 

![image](https://user-images.githubusercontent.com/59060246/119249795-2cce6600-bbb9-11eb-8594-4c19b4496ef4.png)

where as  [my st fork](https://github.com/siduck76/st) of your build (0.8.2) : 

![image](https://user-images.githubusercontent.com/59060246/119249779-014b7b80-bbb9-11eb-8df0-8ccd72ba051f.png)

**Comment by NarutoXY** [comment]
Yeah so just install libxft with bgra patch.

**Comment by siduck76** [comment]
> Yeah so just install libxft with [bgra patch.](https://aur.archlinux.org/packages/libxft-bgra/)

no change 

![image](https://user-images.githubusercontent.com/59060246/124094739-ac800800-da76-11eb-8c7f-97f18b6adb93.png)

this isnt an emoji font problem

**Comment by siduck76** [comment]
Im facing the same issue with any st build of v0.8.3+ . 

my build (0.8.2v)

![image](https://user-images.githubusercontent.com/59060246/124094861-cc173080-da76-11eb-9e8d-8d62179a034b.png)

**Comment by NarutoXY** [comment]
Can you add a padding around glyphs?

**Comment by siduck76** [comment]
> Can you add a padding around glyphs?

no , test logo-ls to reproduce the same issue. on st 0.8.4 . not my build ( since it works on my build)

**Comment by NarutoXY** [comment]
For me it was related to libXft problem. So I fixed that with that and emojis and glyphs worked as they should. st v0.8.4

**Comment by siduck76** [comment]
> For me it was related to libXft problem. So I fixed that with that and emojis and glyphs worked as they should. st v0.8.4

which font do you use?

**Comment by NarutoXY** [comment]
> which font do you use?

Iosevka Nerd font with Twemoji, JoyPixels(Emoji One) and Material Design Icons

**Comment by NarutoXY** [comment]
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Iosevka Nerd Font</family> <!-- Your preferred monospace font -->
      <family>JoyPixels</family> <!-- Your preferred emoji font -->
     </prefer>
  </alias>
</fontconfig>
```
