### ISSUE TITLE
Help removing `alpha` patch

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/st#306]
Hi!

I've been using your build of st but would like to remove the alpha patch (since I don't need it). Going on the suckless website for the alpha patch, it looks like you're using a different one. I would appreciate if you could give me refer me to the code that adds alpha patch functionality to your build.

Thanks.

**Comment by GroosL** [comment]
Yeah I'm trying to remove it as well

**Comment by paniash** [comment]
@GroosL After some help by @bakkeby, I've successfully removed the alpha patch from the build. [This commit](https://github.com/paniash/st/commit/21d57c61a459c8e86c882fdde7d6fbd9a3ea3c98) explains it better.
