### ISSUE TITLE
st crashes upon exiting sxiv

### ISSUE THREAD

**Issue by ZeusThundr** [LukeSmithxyz/st#309]
while in lf the first image always manages to open/close properly but the second (sometimes 3rd or if i'm lucky 4th) image always opens but makes st or maybe even lf unresponsive. It seems to attempt to close it but fails as one of my cores gets stuck around 8 percent until I close st. Note on exit it the only that is shown is a blank terminal window & launching st from another terminal emulator and redoing the steps to reproduce does not produce any error logs. This behavior doesn't seem to happen in other terminal emu. nor on other builds of st just your build not sure why.

Edit: behavior persist on lf and on lf-git
Edit 2: only happens when opening images through lf, fff works fine.
Edit 3: Happens Only when lf sxiv fullscreen mode fills terminal window instead of actually going fullscreen in dwm.

**Comment by SalikMu** [comment]
I have the same issue in a fresh install. Any updates?

**Comment by LukeSmithxyz** [comment]
I've run into this problem too. Not sure what it could be. Probably an error stemming from the interaction between lf and dwm's swallow patch I think.

**Comment by ZeusThundr** [comment]
Issue doesn't appear to happen anymore not sure what fixed it maybe because libxft updated and or some other pkg. Closing this issue.

**Comment by ZeusThundr** [comment]
Moving sxiv flag order to -abio -sf seems to have kinda fixed it. I say kinda because I prefer it to full up the whole terminal window as when It goes in to fullscreen It blocks the view of dmenu, and I am not sure if this fixes the issue on other systems. So this is more of a hack than anything else, I'll let you be the judge whether to close this or not.

**Comment by LukeSmithxyz** [comment]
I'm thinking the problem you have is different from what I thought.

My issue is that sxiv will freeze a swallowed terminal on closure if started from lf. I can't replicate your problem.

**Comment by ZeusThundr** [comment]
Just searched up terminal swallowing as I was unfamiliar with this behavior and yes you what you described is accurate. I just assumed sxiv would go into fullscreen inside the terminal window somehow.

**Comment by LukeSmithxyz** [comment]
Does this issue happen to you when you run sxiv manually from a command line? I only have it when I open a file from lf.

I'm going to guess this is really an sxiv issue, because no other program has this swallowing problem.

**Comment by ZeusThundr** [comment]
No only happens when inside using st and using lf to open up images.

**Comment by LukeSmithxyz** [comment]
Looks like these issues are relevant to the origin of this issue:

https://github.com/muennich/sxiv/issues/342
https://github.com/gokcehan/lf/issues/654

lf seems to have some issues being resized in the background.

This is beyond my control.

**Comment by ZeusThundr** [comment]
Thank you for linking the git issues.
