### ISSUE TITLE
change alpha settings 

### ISSUE THREAD

**Issue by vaskark** [LukeSmithxyz/st#311]
Just wondering where this came from. I can't seem to find the appropriate patch at the st website. I'd like to add it to my own version of st.

Thanks. Great work, btw.

**Comment by wael444** [comment]
if you are talking about terminal transparency, https://st.suckless.org/patches/alpha/

**Comment by vaskark** [comment]
LOL sorry for not being clearer.

I was referencing these settings:

```
float alphaOffset = 0.0;
float alphaUnfocus;
```

and

```
{ MODKEY,					XK_s,				 changealpha,	  {.f = -0.05} },
{ MODKEY,					XK_a,				 changealpha,	  {.f = +0.05} },
```

Allowing a user to change transparency in real time thru keybindings. I don't believe the standard alpha patch is providing this. Must be a custom option added by LS.

**Comment by wael444** [comment]
decided to take https://github.com/LukeSmithxyz/st/commit/73a6020865607018f6442317e7f94fb5d54a7016 and https://github.com/LukeSmithxyz/st/commit/bb56685063532f732f4fbdba1d890931dad3d891 and make them into a patch https://gist.github.com/wael444/c89101e63848c447a4d2ca96f21de6c9 note: this requires alpha.

**Comment by vaskark** [comment]
Many thanks :)

**Comment by wael444** [comment]
please close.
