### ISSUE TITLE
Change st default to bash shell

### ISSUE THREAD

**Issue by BuddhiLW** [LukeSmithxyz/st#320]
I would like that `echo $0 ` would return /bin/bash, by default, instead of /bin/zsh.

In st's config, we have: 

> /*
>  * What program is execed by st depends of these precedence rules:
>  * 1: program passed with -e
>  * 2: scroll and/or utmp
>  * 3: SHELL environment variable
>  * 4: value of shell in /etc/passwd
>  * 5: value of shell in config.h
>  */

But, still, I couldn't understand where it was set in our system.

Regards,
Pedro

**Comment by LukeSmithxyz** [comment]
This isn't relevant to this terminal emulator. Use `chsh` to change your user's default shell.
