### ISSUE TITLE
pywal now working 

### ISSUE THREAD

**Issue by golam47** [LukeSmithxyz/st#328]
according to pywal docs 
`printf "%b" "\033]11;#ff0000\007" `
should make my terminal background red but it does not make it red

**Comment by terriblephrases** [comment]
If you check https://github.com/LukeSmithxyz/st/blob/master/st.c#L1933 you'll see OSC escape code `]11` (set background) is not defined, while OSC escape code `]4` (set color) is defined. If you check https://github.com/LukeSmithxyz/st/blob/master/config.h#L146 you'll see the background is color number 258.

Therefore, use `"\033]4;258;#ff0000\007"` instead.
