### ISSUE TITLE
Unicode rendering/CJK input issues

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/st#329]
## All wide characters get cut off in the top side
![pic-selected-220502-1756-25](https://user-images.githubusercontent.com/96898325/166209746-8bbd030c-a1e1-4042-8c5d-b6e9982bde66.png)
As you can see, all multibyte characters' tops get cut off, such as emojis or CJK characters. I don't think this is a font related issue, and this isn't related to #223 too, since that already got fixed.
## Flags overlap with the country code
![pic-selected-220502-1759-51](https://user-images.githubusercontent.com/96898325/166210186-d7fab75b-254d-4dad-9f14-f219421539ad.png)
The country flag emojis somehow overlap with their country code, as shown in the screenshot, and the characters tend to mush together if written side by side.
## CJK Input creates a secondary small window
![pic-selected-220502-1832-10](https://user-images.githubusercontent.com/96898325/166214167-9156ff76-6455-4e79-b193-943811932f66.png)
This is not that big of an issue, since the input still works correctly. This happens because the input method is using GTK/Qt but st doesn't use any toolkit out there, so the input method basically emulates the multibyte input sequence with a small pre-window(as I like to call it) before the input actually gets registered. I'm pretty sure this problem won't go away unless an incredible amount of bloat is added, so I don't think it deserves a fix. However I'm leaving it up here so people can confirm the issue does exist and it's not only them that's having the issue.

**Comment by kskeigrshi** [comment]
Seems like the characters are not cut off when the font size is very small. Maybe dynamically increasing the height of a single line could be the solution to this problem.

**Comment by askfiy** [comment]
Well, won't this problem be fixed? Is there a viable solution?

**Comment by LukeSmithxyz** [comment]
This is a library issue apart from this repo. Have fontconfig or st lessen the size of emojis to compensate.
