### ISSUE TITLE
Alt+l linkhandler issue

### ISSUE THREAD

**Issue by hexinal** [LukeSmithxyz/st#34]
My dmenu does appear and extract links but doesn't seem to be able of opening anything. Using linkhandler separately does work though.

**Comment by LukeSmithxyz** [comment]
If you're using `linkhandler` it's possible that there was some error or delay in opening something. I.e. if you selected a YouTube video, it will try to open in mpv and will not show errors or if your connection is bad, will be delayed.

I've actually just pushed a change that reverts the program used to open links to `xdg-open` for compatibility with people not using LARBS. I might make a more robust solution later.

**Comment by wandy-dev** [comment]
@hexinal I noticed the same issue so I tried running `sudo su` and then `cat file_with_urls | xurls | dmenu` and replicated the issue. I fixed it by copying the executable for `xurls` to `/usr/local/bin`
