### ISSUE TITLE
libxft-bgra seems to be removed from the AUR

### ISSUE THREAD

**Issue by AlopexTMNT** [LukeSmithxyz/st#343]
So, when you try to download libxft-bgra from the AUR as Luke suggested [libxft-bgra from AUR](https://aur.archlinux.org/packages/libxft-bgra) it shows you a 404 error which suggests that the package has been removed. Searching for it in the AUR gave me these results [1st result](https://aur.archlinux.org/packages/libxft-bgra-git) and [2nd result](https://aur.archlinux.org/packages/lib32-libxft-bgra).
St doesn't seem to crash without it, at least for me. Just pointing it out that the original package is nowhere to be found.

**Comment by LukeSmithxyz** [comment]
README now changed. The relevant package is now libxft-git until the new version of libxft comes out and it becomes unnecessary.
