### ISSUE TITLE
Problem showing emojis in st and dmenu

### ISSUE THREAD

**Issue by iStagnant** [LukeSmithxyz/st#346]
I am having some problems with emojis in both st and dmenu, if i press `Mod+~` to show the icon picker some emojis show an empty box next to them
![image](https://user-images.githubusercontent.com/82290573/202020159-210a75fd-bf34-4217-93f0-4c5a36cc69bd.png)
and if i paste theme to st they look like this
![image](https://user-images.githubusercontent.com/82290573/202020885-fed68921-3154-48e0-b385-05dd72b72887.png)
as you can see there is `<fe0f>` at the right side of the emoji and if i remove it half of the emoji is gone, but strangely whether i remove that bit at the end or not if i press enter zsh will return that no command was found but it will always display the emoji correctly, so can this be fixed?

**Comment by 2084x** [comment]
try installing `ttf-dejavu` to get rid of the boxes

**Comment by iStagnant** [comment]
> try installing `ttf-dejavu` to get rid of the boxes

Installing `ttf-dejavu` does indeed remove the boxes and when i paste the emoji to the terminal it still shows the `<fe0f>` but if i delete it the emoji doesn't get chopped in half anymore, though I'm not sure if this is because of the font or because of the patch in the PR i made, anyways this is good enough for me thank you for your help.
