### ISSUE TITLE
ctrl-l doesn't work when a program is running

### ISSUE THREAD

**Issue by ZulluBalti** [LukeSmithxyz/st#348]
Hi,

Is there any way for ctrl-l to clear the screen when a program is already running in st.

For example when I run `npm run dev` and after some time when there is a lot of text on the terminal I want to clear the terminal. Pressing ctrl-l doesn't work as the program is running.

I know i can do ctrl-z then clear then fg to achieve the same result but I want a shortcut (keybinding) to it.

In VSCODE terminal I had a keybinding setup that would do that.

**Comment by LukeSmithxyz** [comment]
No.

**Comment by ZulluBalti** [comment]
any post/tutorial to make it work?
