### ISSUE TITLE
applied a colorscheme with pywal and now it won't go away for anything in this world

### ISSUE THREAD

**Issue by Vinni-Cedraz** [LukeSmithxyz/st#352]
The only way to change it seem to be by generating another pywal colorscheme and that is not what I want.
I even deleted pywal cache, UNINSTALLED pywal even and the colorscheme wont go away.
Please help me I'm considering even calling a priest to exorcise this colorscheme out of here.

**Comment by LukeSmithxyz** [comment]
Go ask pywal, not me. Probably put some colors in an xresources or xdefaults file that st uses.
