### ISSUE TITLE
alpha is not working

### ISSUE THREAD

**Issue by lucaspeixotot** [LukeSmithxyz/st#38]
Hello, I'm using st for the first time and apparently everything is working good, except for the alpha config. No matter what value I set both in config.h or in .Xresources, the background remains solid. 

ps: I'm remembering to use xrdb .Xresources after .Xresources changes and I'm remember to compile when I change config.h as well.

Someone knows what this could be?

**Comment by LukeSmithxyz** [comment]
Do you have a composite manager running like compton or xcompmgr?

On January 6, 2019 11:41:24 PM EST, Lucas Peixoto de Almeida Cavalcante <notifications@github.com> wrote:
>Hello, I'm using st for the first time and apparently everything is
>working good, except for the alpha config. No matter what value I set
>both in config.h or in .Xresources, the background remains solid. 
>
>ps: I'm remembering to use xrdb .Xresources after .Xresources changes
>and I'm remember to compile when I change config.h as well.
>
>Someone knows what this could be?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LukeSmithxyz/st/issues/38

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucaspeixotot** [comment]
Ohh I think no, is there something special in its installations or is just sudo apt install etc...?

I don't know if I should know that I should install compton, I'm relatively new in this stuff.

**Comment by LukeSmithxyz** [comment]
Just install one and have it run when you start your graphical environment. It's typically required for effects like transparency.

**Comment by lucaspeixotot** [comment]
Thanks, everything is working now, your videos are really great!
