### ISSUE TITLE
image preview with black stripes

### ISSUE THREAD

**Issue by lucaspeixotot** [LukeSmithxyz/st#39]
I was using urxvt and the ranger image preview was working. With urxvt I didn't use compton. With st I began to use compton and with it my ranger preview image broke.

The image below shows what is happening.

![15h_13min_48sec-07 01 2019_](https://user-images.githubusercontent.com/11475476/50785956-e9495a80-1290-11e9-9138-b66c573b5124.png)

I don't have any compton configuration, I just installed. Someone know what should I do?

Here is my rc.conf
```
set preview_script ~/.config/ranger/scope.sh
set use_preview_script true
set preview_images true
set preview_images_method w3m
set preview_files true
set preview_directories true
set draw_borders true
```
ps: When I kill compton process everything works fine. I don't know exactly if the problem is with st + ranger + compton or if is just ranger+compton problem, but maybe someone could help me.

**Comment by dawidpotocki** [comment]
You can try using Ueberzug instead of w3m, it works a lot better for me. I guess you use Ubuntu (hostname) so:

```
sudo apt install python-pip
sudo pip3 install ueberzug
```

Then install latest ranger from [git repository](https://github.com/ranger/ranger):

```
sudo apt install git
git clone https://github.com/ranger/ranger.git
cd ranger
sudo make install
```

And finally edit your `rc.conf` like that:

```
set preview_images true
set preview_images_method ueberzug
```

**Comment by lucaspeixotot** [comment]
I switched to nnn, so I will closed this issue because of that.
