### ISSUE TITLE
Transparency does not work

### ISSUE THREAD

**Issue by daviur** [LukeSmithxyz/st#41]
Hi Luke, thank you so much for your amazing amount of work setting LARBS and making your videos. 

I am testing LARBS and I am having problems to get the transparency on st working. I have changed the alpha value on the .Xresources but nothing. And yes, "xrdb .Xresources" is automatically called by your .vimrc.

Any ideas?

**Comment by daviur** [comment]
Thanks! Effectively xcompmgr was not installed. I am using your dot files on ubuntu. I did not used your install scripts. Do you have a requirements guide for people who want to use LARBS but want to set everything by hand?
Thanks again.

**Comment by LukeSmithxyz** [comment]
The readme links the `progs.csv` file which contains all the dependencies with an explanation. Direct link here: https://github.com/LukeSmithxyz/LARBS/blob/master/progs.csv.
