### ISSUE TITLE
Ranger theme does not work

### ISSUE THREAD

**Issue by N214** [LukeSmithxyz/st#42]
Hi,

Somehow I can't manage to get my ranger theme to work with st and I don't know why? Have anyone experience that? Thanks !
 
![screenshot from 2019-01-12 18-53-13](https://user-images.githubusercontent.com/34739662/51076770-58fa8380-169d-11e9-99fd-e31ce2eeca5d.png)

**Comment by LukeSmithxyz** [comment]
How have you created themes/set colors in ranger specifically? How does it look in other terminal emulators?

**Comment by Bibobu** [comment]
Hi Luke,
In a similar way I downloaded your fork of st right after installing Arch and xorg (more or less the basic packages you recommended in your video on the topic). I understood that I could define the colors in the .Xresources file so I made those two files in my home directory:
.xinitrc:
```
#!/bin/sh
exec i3
[ -f ~/.Xresources ] && xrdb -merge  ~/.Xresources
```
.Xresources:
```
! The colours I try to put in
*,color1:#000000
*.color2:#ff4d83
...
```

And so on with 16 colours for dark and bright versions. Yet my terminal colours does not change. I also tried to replace the default colours in the config.h file without any other results. I suspect I'm not the only one in this situation. Any suggestion?

Regards.

Btw, I switched from Debian to Arch thanks to you and my old machines gained a significant improvement in speed without DE taking all the resources. Thanks for the tutorials.
