### ISSUE TITLE
Pressing `v` in command mode opens vim

### ISSUE THREAD

**Issue by pyaf** [LukeSmithxyz/st#45]
Hi, I absolutely love your st fork. When in command mode pressing `v` opens vim. I want to remove this shortcut. I've looked into `config.h` but I didn't find where this shortcut is defined!. (`shotcuts[]` doesn't contain this shortcut). Your LARBS's bashrc file defines an alias v as $EDITOR (vim by default). But I dont' this that has anything to do with pressing `v` in command mode in your st. Please help!

**Comment by LukeSmithxyz** [comment]
This is not a part of st. Turn off your shell's vi bindings. If you are using LARBS, these are set in `~/.inputrc`. Delete the file entirely or just remove the `set editing-mode vi` line. Logging out/in may be necessary.

You could also read the man for `readline` and learn how to only disable that bind if you want to keep the other vi bindings.

**Comment by pyaf** [comment]
Thanks.
