### ISSUE TITLE
is it possible to open vim in st via i3-msg and let it stay open?

### ISSUE THREAD

**Issue by divramod** [LukeSmithxyz/st#50]
i want to run a bash script which opens a file on another i3 workspace in vim in st.
it looks somehow like that:

```
i3-msg "workspace 5"
i3-msg "exec st vim /some/file"
```

the problem is, when i run st like this
```
st
```
it opens like i would expect it.

when i run st like this
```
st -e "vim /some/file"
```
st closes instantly after launching.

How can i achieve that st stays open with vim already open?

btw really awesome work you did with larbs!!!!

**Comment by TpouHuK** [comment]
`st -e "vim /some/file"` will open command "vim /some/file" with no arguments.
results: 

- fish - Unknown command 'vim /some/file'
- zsh - zsh: no such file or directory: vim /some/file
- sh - sh: vim /some/file: No such file or directory

`st -e vim /some/file` or `st -e "vim" "/some/file"` should do what you want

**Comment by divramod** [comment]
thank you. solved my problem
