### ISSUE TITLE
Terminal Cursor

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/st#51]
![pic-full-190221-2117-43](https://user-images.githubusercontent.com/47856573/53171915-0d81b080-361f-11e9-8fb7-fa03512b59a4.png)
Hi, maybe I'm too dumb to realize the problem but why is my terminal cursor a vertical line instead of block shape like how it is in Luke's video. I fresh installed Arch Linux and install Larbs. I have also tried installing the Luke's st build but the cursor still remain as vertical line. When going into Vim, the cursor turns to block shape. After quit Vim, it turns back to vertical line. Anyone know how to fix this?

**Comment by pRot0ta1p** [comment]
in luke's .inputrc, he has
```
set vi-ins-mode-string \1\e[6 q\2
set vi-cmd-mode-string \1\e[2 q\2
```
this settings will change the cursor in a line shape when in insert mode, and box shape in normal mode.
because he use vi mode in bash,  this can be a nicer way of mode indicating.
also checkout https://wiki.archlinux.org/index.php/Readline
