### ISSUE TITLE
[LARBS] Transparency not working after using pywal

### ISSUE THREAD

**Issue by emorevival** [LukeSmithxyz/st#54]
Hey Luke, 

I'm on a fresh Archlabs install and just used pywal on a wallpaper I have. Everything applied well, even in st, but now the windows aren't transparent like they were before. I added `*.alpha = 255` (tried other values too) to my .Xresources, I've checked the st config file and recompiled that as well but it's still the same.

I haven't changed the default compton config that is installed by LARBS.

edit: just to clarify, it was working before I used pywal

**Comment by emorevival** [comment]
hmmm, transparency seems to work on (popup?) terminal windows. Your pacman updates module notified me that there are 8 updates and when I clicked it the window that was opened by it had the exact transparency I had set in `.Xresources`.

**Comment by ask6155** [comment]
Only my popup terminal have transparency. Rest all don't. Happened with the latest update.

**Comment by emorevival** [comment]
my exact issue too except for me the rest of them do too but only if you launch a specific cli program through a keybinding like `$mod+r`

**Comment by jpnadas** [comment]
I don't use LARBS, but I have just updated luke's st build on my arch install and transparency stopped workign for me as well (I set alpha via .Xresources).

**Comment by LukeSmithxyz** [comment]
In every case, your `xrdb` settings are set in a way inconsistent or overriding of the settings of st. I have no clue what the defaults are for Archlabs or Manjaro or any of those other distributions, so if anyone could give me the output of `xrdb -query` or their `~/.Xdefaults` or `~/Xresources` files, I could figure it out.

@jpnadas Your problem is due to a recent upgrade. Now, the `alpha` value required should be a floating point between `0` (fully transparent) and `1` (fully opaque). Change that and it should be fixed.

**Comment by emorevival** [comment]
[Here is the output of xrdb -query](https://pastebin.com/QWdKV499) and [here's my ~/Xresources file](https://pastebin.com/eQVXEX3F)

**Comment by LukeSmithxyz** [comment]
What composite manager do you have running?

**Comment by emorevival** [comment]
compton, this is my [`compton.conf`](https://pastebin.com/2TRfgPWh)

**Comment by LukeSmithxyz** [comment]
I'm not able to replicate this problem even with pywal and your compton config. Are you using the most recent build?

Exactly what wal command are you running?

**Comment by emorevival** [comment]
This is the output of `st -v`: 

`st 0.8.1 (c) 2010-2016 st engineers`

for pywal I'm running `wal -i image`, through the "bw" shortcut in your `ranger` config in LARBS

**Comment by jpnadas** [comment]
> @jpnadas Your problem is due to a recent upgrade. Now, the `alpha` value required should be a floating point between `0` (fully transparent) and `1` (fully opaque). Change that and it should be fixed.

Thanks @LukeSmithxyz, that did it!

**Comment by jpnadas** [comment]
> [Here is the output of `xrdb -query`](https://pastebin.com/QWdKV499) and [here's my `~/Xresources file`](https://pastebin.com/eQVXEX3F)

am I missing something or shouldn't you just uncomment the `!*.alpha : 255` from your .Xresources and change the value to something in the range [0,1]?

**Comment by emorevival** [comment]
> > [Here is the output of `xrdb -query`](https://pastebin.com/QWdKV499) and [here's my `~/Xresources file`](https://pastebin.com/eQVXEX3F)
> 
> am I missing something or shouldn't you just uncomment the `!*.alpha : 255` from your .Xresources and change the value to something in the range [0,1]?

that's commented out from when I was trying to fix it, I didn't even have it there before using pywal and trying to fix the issue. either way, it doesn't seem to make a difference (well technically: it does make a difference when I launch ranger from a keybinding or launch the floating terminal, but the terminal launched with `$mod+Enter` (or just with `st`) is still not transparent like the rest). like so:

![image](https://user-images.githubusercontent.com/32765662/57714444-d39bd580-7674-11e9-9be5-01532803f1bb.png)

see how all other windows launched by a keybinding have the correct transparency but not the regular one?

**Comment by codeitlikemiley** [comment]
check your st build guys, the latest build dont use 0-255 it uses 0-1. the lesser the vale the more transparent the terminal is.

**Comment by NicholasFarrow** [comment]
@emorevival I got transparency by using compton, 
https://github.com/LukeSmithxyz/st/issues/46

`opacity-rule = [ "90:class_g = 'St'" ];` in `~/.config/compton.conf`

**Comment by KjOHnBaggins** [comment]
I have the same problem, too. Transparency working with xcompmgr but when I installed pywal and run wal -i ./img.jpg, it just loses transparency, but all the other colors are working. I also have the st alpha patch, and set the float value to 0.5, but it still doesn't seem to work.
