### ISSUE TITLE
Using light themes don't seem to work with the st.

### ISSUE THREAD

**Issue by DrDonkey** [LukeSmithxyz/st#56]
I am trying to use Gruvbox light with st and it doesn't seem to work. I tried with Solarized dark too, but didn't work.

**Comment by LukeSmithxyz** [comment]
What exactly do you mean by "doesn't seem to work"?

**Comment by DrDonkey** [comment]
The colorschemes don't apply. For example If I set [Solarized Light](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/Xresources/Solarized%20Light) then I get solarized dark as applied color scheme.

**Comment by LukeSmithxyz** [comment]
So dark themes do work? What does `xrdb -query` show when you've set light colors?

**Comment by DrDonkey** [comment]
My bad. That is the theme problem using [gruvbox-light](https://github.com/morhetz/gruvbox-contrib/tree/master/xresources) worked.
