### ISSUE TITLE
Colored emojis and crashes

### ISSUE THREAD

**Issue by andremeireles** [LukeSmithxyz/st#58]
After a upgrade, some text editors and file managers closes almost instantly on opening and previewing text files with colored emojis inside.
Before the upgrade i was able to open and preview these same text files with the same applications listed below.

ST terminal was open while the update was in progress because i did a command-line request.
I did the reboot a couple hours later. Maybe 6h or 8h after the update.

Manjaro-i3

editor: vim, nano
file managers: vifm, ranger, lf, nnn
others: newsboat, neomutt
Emoji font installed: EmojiOne (installed at distro install), noto-fonts-emoji (installed at 2019/04/01)

* If i do the same task with others terminal emulators (urxvt, xterm), the file is opened or previewed but none emoji is visible.
* If i do the same task with GUI applications (sublime-text, mousepad) , the text files are opened and the emojis are visible.
* Emojis still be visible at i3bar.

The upgrade was at 2019/03/30 ==> [PACMAN.LOG at pastebin.com](https://pastebin.com/i9jj32iy)
The [.Xresources at pastebin.com](https://pastebin.com/Q92mdEDY)

**Comment by andremeireles** [comment]
Installing `ttf-symbola` solve the issue.

**Comment by mvdan** [comment]
@andremeireles just passing by to say that your comment saved my morning :) I had the exact same issue.

**Comment by andremeireles** [comment]
You're welcome @mvdan. I am glad to hear it.
