### ISSUE TITLE
Wide unicode characters get cut off

### ISSUE THREAD

**Issue by Sermak-GIT** [LukeSmithxyz/st#59]
Wide emojis get cut off when displayed in certain applications.

For example, compare newsboat in st
![image](https://user-images.githubusercontent.com/15004441/55827262-0d277100-5b0a-11e9-86d3-bbce3b155086.png)
with newsboat in alacritty
![image](https://user-images.githubusercontent.com/15004441/55827415-655e7300-5b0a-11e9-9e34-6943d23d93fe.png)
This is not an issue of the font, I tested multiple for both terminal emulators. In other applications, such as (neo)vim, the emoji covers the following char as long as that char is not highlighted.
![image](https://user-images.githubusercontent.com/15004441/55827556-be2e0b80-5b0a-11e9-986f-fef1cfcee3da.png)

**Comment by hydrocodone-senpai** [comment]
Try setting your system locale. I had similar issues with unicode characters being placed too close together and then getting cut off by subsequent characters. Try 
`% localectl`
and if it is not [something].utf8, make sure to set it. For me, running:
`% localectl set-locale LANG=en_US.utf8`
followed by a restart fixed my issue.
