### ISSUE TITLE
delete word cursor shift to right

### ISSUE THREAD

**Issue by peet1234** [LukeSmithxyz/st#71]
Hi Luke I'm install your st-luke-git from AUR, and i have some problem. when i delete word in st, and the cursor shift to right . please see the screen shot.
![win0509-11:01:33](https://user-images.githubusercontent.com/37007880/57426644-43135e80-724a-11e9-80ec-a03808ff7518.png)
![win0509-11:01:48](https://user-images.githubusercontent.com/37007880/57426652-4a3a6c80-724a-11e9-9893-cd363153516c.png)

**Comment by rjl6789** [comment]
Yes - I have observed this behaviour as well.  What's the output of `$TERM` - it should be `st-256color` - on mine it was some hex color code. 
Looking at the `config.h` in the git repo I notice that there is a line:
` { "cursorColor",  STRING,  &colorname[258] },`
i.e. the array colorname has its 258th element assigned to cursorColor string - for reading from the .Xresources/.Xdefaults file.

Unfortunately - when the array `colorname` is defined (a number of lines above) - it is only defined up to 257 items.  The last line being:
`"white",   /* 257 -> fg */`
if you add another line to define a 258th item - (the cursor color)
`"#add8e6", /* 258 -> cursor */`

and then recompile - all is ok.

This won't help the aur version - the git version needs updating then the changes incorporated into the aur package by whoever maintains it.

I've never done a pull request before - but will see give it a shot and see if I can get this change incorporated

**Comment by rjl6789** [comment]
well - I've given it a go #72 - hopefully I've done it correctly.  If not it will get rejected!

**Comment by jsav0** [comment]
Great input rjl6789! What a catch! That fix works for me :beers:

**Comment by rjl6789** [comment]
Thanks! - I note @LukeSmithxyz  has merged the changes - so this should now be closed I think?  Is it now working for you @peet1234 ?  If you aur update ( `yay -Syu` ) I'm guessing it will pull in the update.  Thanks @LukeSmithxyz for merging in the pull request.

**Comment by loeschzwerg** [comment]
I had exactly the same issue this morning. 
I just updated via `pamac build` on manjaro and the issue has been resolved.
Great work! Thanks a lot @rjl6789
