### ISSUE TITLE
Problem with Thai Font

### ISSUE THREAD

**Issue by peet1234** [LukeSmithxyz/st#74]
I'm Thai , in Thai language have something call vowel, like  "  ั " in urxvt is normal everything is fine.
in st (see screen shot)
![2019-05-10_13-32](https://user-images.githubusercontent.com/37007880/57507590-6f51dc80-7329-11e9-9d1b-2dfa3a7cb65e.png)
on Left is Urxvt , ST on the right
I have edit config.h to use Thai font and make ,make install , still not working.
Thank you Luke.

**Comment by LukeSmithxyz** [comment]
This is not an st problem, but a font problem. If you look carefully, you are using different fonts in urxvt for both Latin and Thai characters.

By default, st looks to your system default mono font. You can change this to change to font.
