### ISSUE TITLE
Support for multiple buffers

### ISSUE THREAD

**Issue by MuresanVladMihail** [LukeSmithxyz/st#76]
It would be interesting to have support for multiple buffers so I don't open N tabs every time I want to do something.

**Comment by LukeSmithxyz** [comment]
What do you mean by a "buffer" in the context of a terminal emulator?

**Comment by MuresanVladMihail** [comment]
![Screenshot_2019-05-10_18-55-02](https://user-images.githubusercontent.com/48010567/57540424-5f4ff200-7355-11e9-89f7-01d9bf5ec936.png)

**Comment by LukeSmithxyz** [comment]
I don't understand. How is that different from a tab?
