### ISSUE TITLE
ZSH autocompletion left-over characters

### ISSUE THREAD

**Issue by Eksapsy** [LukeSmithxyz/st#80]
I have left over characters when I autocomplete with **zsh-autosuggestions**. 

For example
```bash
$ echo <TAB>(autocompletes)
$ echoecho "Hello world"
# clears all text and this is left that cannot be removed
$ echo
```

I had this issue with urxvt and st, but never with gnome-terminal. Which probably implies that this is not a zsh issue, but a terminal issue. Or maybe not. Hope I will get some guidance here.

But I have no idea why this happens, any ideas? I could probably start debugging and make a patch maybe, if it's not too complicated.

**Comment by codeitlikemiley** [comment]
try adding this to your .zshrc
```
zstyle ':completion:*' completer _expand_alias _complete _ignored
```
