### ISSUE TITLE
Is there a patch where we can add font ligatures?

### ISSUE THREAD

**Issue by codeitlikemiley** [LukeSmithxyz/st#81]
I got a font with ligatures it would be awesome if i can use those font ligatures like in Fira Code.
Is there a way to patch this?

**Comment by codeitlikemiley** [comment]
I did make a patch called font2 but it is manually patch.
Now i can have glyphicons in the st terminal without any problem

![2019-05-15-115339_1920x1080_scrot](https://user-images.githubusercontent.com/28816690/57747479-4bffa680-7708-11e9-8eb1-a58780b12df5.png)

**Comment by andys8** [comment]
@codeitlikemiley But `font2` won't help with ligatures, right? Glyphicons aren't ligatures.
