### ISSUE TITLE
Ctrl + "=" and Ctrl + "-" to Zoom?

### ISSUE THREAD

**Issue by ryanerwin** [LukeSmithxyz/st#82]
Luke,

I'm new to ST... Heard about it from your YouTube video...

I've been tweaking `config.h` to get it more to my liking, but I'm not understanding how the shortcut keys work and I haven't been able to find enough documentation to figure out the way new keyboard shortcuts are mapped...

```
173   { TERMMOD,              XK_Prior,       zoom,           {.f = +1} },
174   { TERMMOD,              XK_Next,        zoom,           {.f = -1} },
```

By default it seems to work with:
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>PageUp</kbd> 
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>PageDown</kbd>

But how would I make this work with <kbd>Ctrl</kbd> + <kbd>=</kbd> and <kbd>Ctrl</kbd> + <kbd>-</kbd> is ST?

There is some good `keysym` documentation at:
https://wiki.archlinux.org/index.php/Xmodmap

Yet I still haven't figured out make the shortcut work...

Do I need to extend `static Key key[] =` to include the keycode that I want to use since there isn't already an `XK_Equals` and `XK_Minus`?

Inside of `static Shortcut shortcuts[] =` would it be something like?

```
  { ControlMask,          XK_Equals,       zoom,           {.f = +1} },
  { ControlMask,          XK_Minus,       zoom,           {.f = -1} },{ 
```

If so, would string would I define for `XK_Equals` and `XK_Minus` in `static Key key[]`?

Using `xev` I get:
```
37  Control_L
21  equal
37  Control_L
20  minus
```

Thanks for any help you can offer.

**Comment by CodingLappen** [comment]
https://code.woboq.org/qt5/include/X11/keysymdef.h.html

Look at line 543 and below that. The keys you might want to know are defined there.

**Comment by ryanerwin** [comment]
Thanks for the tip @CodingLappen 

So I was able to make this work by only editing the `static Shortcut shortcuts[]` array, adding:

```
	{ ControlMask,          XK_equal,       zoom,           {.f = +1} },
	{ ControlMask,          XK_minus,       zoom,           {.f = -1} },

```

The shortcut key works well.

**Comment by sonsais** [comment]
> Thanks for the tip @CodingLappen
> 
> So I was able to make this work by only editing the `static Shortcut shortcuts[]` array, adding:
> 
> ```
> 	{ ControlMask,          XK_equal,       zoom,           {.f = +1} },
> 	{ ControlMask,          XK_minus,       zoom,           {.f = -1} },
> ```
> 
> The shortcut key works well.

didn't work for me. no shortcut listed on that site works
any idea as to why?

**Comment by ryanerwin** [comment]
I'm not sure if the base st code has changed so that perhaps it's no longer compatible.

Most recently I've been using kitty because I enjoy the GPU based rendering speed and ligature support, but I still love minimal tools like St.

I would start by trying to patch this into a st release from 2019 and see if it works. If it does, then probably the shortcut support in st has probably changed enough that the patch process is different.

If it doesn't work, it's probably something strange on your machine. Maybe your keyboard layout. Maybe an input method. Maybe your window manager.

I would start by narrowing down the possibilities.

On Sat, Feb 4, 2023, at 18:39, sonsais wrote:
> 
> 
>> Thanks for the tip @CodingLappen <https://github.com/CodingLappen>
>> 
>> So I was able to make this work by only editing the `static Shortcut shortcuts[]` array, adding:
>> 
>> `	{ ControlMask,          XK_equal,       zoom,           {.f = +1} },
>> 	{ ControlMask,          XK_minus,       zoom,           {.f = -1} },
`

**Comment by mmngreco** [comment]
@ryanerwin I have the same problem. I've tried others XK (like XK_greater/XK_less) without success. did you solve it?
