### ISSUE TITLE
Gotop graphs don't work.

### ISSUE THREAD

**Issue by Stupremee** [LukeSmithxyz/st#92]
I recently switched to Arch and use this st fork as my terminal. But Gotop doesn't work properly. The terminal doesn't display Gotop's graphs correctly. It worked in URxvt, but not in st. I don't know if it's a bug on my part or on st. 

It should look like this:
![gif](https://raw.githubusercontent.com/cjbassi/gotop/master/assets/demo.gif)

but for me it looks like this:
![png](https://i.imgur.com/6QjLjD6.png)

As you can see, it doesn't show the graphs.

**Comment by LukeSmithxyz** [comment]
My st build uses your default monospace font, and whatever your font is, that's probably the issue.

I just tried gotop on my machine with my st and it werks fine (although the bars are thicker on top, but that's also probably font dependent). My monospace font is inconsolata.

**Comment by Stupremee** [comment]
Okay I will try another font later.
