### ISSUE TITLE
Xresources/Xrdb color not respected

### ISSUE THREAD

**Issue by wundrweapon** [LukeSmithxyz/st#97]
When setting colors through Xrdb's `.Xresources` or `.Xdefaults`, color options are not used, instead preferring the constants set in the `colorname` array in `config.h`.  
None of the following lines produce a completely-white background:
```
*.color0: #ffffff
*.color0: #111
*.color256: #ffffff
*.color256: #111
*.color257: #ffffff
*.color257: #111
```
Nor will `*.color258: #000000` or `*.color258: #000` produce a black cursor.

Thus, somewhere the Xrdb support is failing for color. Interestingly, font works as intended; setting `*.font` with `pixelsize=42` produces large text as expected

**Comment by pRot0ta1p** [comment]
try lookup your *.alpha value, since luke changed the value range from 0~255 to 0~1, use 
`*.alpha: 1
`
solve the problem for me.

**Comment by wundrweapon** [comment]
I've already switched my `*.alpha` to `.8` from `204` in a previous version, so that shouldn't be the cause

**Comment by sarpik** [comment]
@wundrweapon I found the fix, take a look at #108 :)

**Comment by aleksfadini** [comment]
Yea, in my case using pywal, for instance, changes the current st instance to non sense colors, but all the new ones, launching st again, will behave correctly. Something is wrong with the colors

**Comment by wundrweapon** [comment]
Thank you @sarpik; your PR was the example I needed!
